apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: radarr
  namespace: media
spec:
  backup:
    barmanObjectStore:
      destinationPath: s3://trdos-me--volsync/cnpg/radarr/
      endpointURL: https://s3.us-west-004.backblazeb2.com
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: radarr-b2-postgres
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: radarr-b2-postgres
    retentionPolicy: 30d
  bootstrap:
    initdb:
      database: radarr
      owner: radarr
      postInitApplicationSQL: []
      postInitSQL: []
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  instances: 1
  monitoring:
    enablePodMonitor: true
  postgresql:
    shared_preload_libraries: []
  serviceAccountTemplate:
    metadata:
      name: radarr-pg
  storage:
    size: 5Gi
    storageClass: ceph-block
