apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
  namespace: media
spec:
  data:
    - remoteRef:
        key: radarr
      secretKey: RADARR__AUTH__APIKEY
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: radarr-app
        property: password
      secretKey: RADARR__POSTGRES__PASSWORD
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-media
