apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-vpn
  namespace: media
spec:
  data:
    - remoteRef:
        key: vpn/wireguard/private-key
      secretKey: WIREGUARD_PRIVATE_KEY
    - remoteRef:
        key: vpn/wireguard/addresses
      secretKey: WIREGUARD_ADDRESSES
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
