apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: ory/argocd/client-id
      secretKey: oidc.argocd.clientID
    - remoteRef:
        key: ory/argocd/client-secret
      secretKey: oidc.argocd.clientSecret
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    creationPolicy: Merge
    name: argocd-secret
