apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: argocd
        property: CLIENT_ID
      secretKey: oidc.argocd.clientID
    - remoteRef:
        key: argocd
        property: CLIENT_SECRET
      secretKey: oidc.argocd.clientSecret
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-identity
  target:
    creationPolicy: Merge
    name: argocd-secret
