apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: argocd-admin
  namespace: cicd
spec:
  data:
    - match:
        remoteRef:
          remoteKey: argocd/admin-password
        secretKey: password
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: bitwarden
  selector:
    secret:
      name: argocd-initial-admin-secret
