apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: argocd-in-cluster
  namespace: cicd
stringData:
  config: '{"tlsClientConfig":{"insecure":false}}'
  name: in-cluster
  server: https://kubernetes.default.svc
