# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

accessToken: Optional[str]
"""
Machine Account Access Token (env: `BWS_ACCESS_TOKEN`)).
"""

clientId: Optional[str]
"""
Client ID (env: `BW_CLIENTID`)
"""

clientImplementation: Optional[str]
"""
Client implementation type. Valid values are "embedded" (use embedded client) or "cli" (use CLI binaries, default).
"""

clientSecret: Optional[str]

email: Optional[str]
"""
Login Email of the Vault (env: `BW_EMAIL`).
"""

experimentals: Optional[str]
"""
Enable experimental features.
"""

extraCaCerts: Optional[str]
"""
Extends the well known 'root' CAs (like VeriSign) with the extra certificates in file (env: `NODE_EXTRA_CA_CERTS`, doesn't work with embedded client).
"""

masterPassword: Optional[str]

server: Optional[str]
"""
Bitwarden Server URL (default: `https://vault.bitwarden.com`, env: `BW_URL` or `BWS_SERVER_URL`).
"""

sessionKey: Optional[str]
"""
A Bitwarden Session Key (env: `BW_SESSION`)
"""

vaultPath: Optional[str]
"""
Alternative directory for storing the Vault locally (default: `.bitwarden/`, env: `BITWARDENCLI_APPDATA_DIR`; set to empty string to use CLI default).
"""
