# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys
import pulumi
import pulumi.runtime
from typing import Optional

if sys.version_info >= (3, 11):
    pass
else:
    pass

import types

__config__ = pulumi.Config("bitwarden")


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def access_token(self) -> Optional[str]:
        """
        Machine Account Access Token (env: `BWS_ACCESS_TOKEN`)).
        """
        return __config__.get("accessToken")

    @_builtins.property
    def client_id(self) -> Optional[str]:
        """
        Client ID (env: `BW_CLIENTID`)
        """
        return __config__.get("clientId")

    @_builtins.property
    def client_implementation(self) -> Optional[str]:
        """
        Client implementation type. Valid values are "embedded" (use embedded client) or "cli" (use CLI binaries, default).
        """
        return __config__.get("clientImplementation")

    @_builtins.property
    def client_secret(self) -> Optional[str]:
        return __config__.get("clientSecret")

    @_builtins.property
    def email(self) -> Optional[str]:
        """
        Login Email of the Vault (env: `BW_EMAIL`).
        """
        return __config__.get("email")

    @_builtins.property
    def experimentals(self) -> Optional[str]:
        """
        Enable experimental features.
        """
        return __config__.get("experimentals")

    @_builtins.property
    def extra_ca_certs(self) -> Optional[str]:
        """
        Extends the well known 'root' CAs (like VeriSign) with the extra certificates in file (env: `NODE_EXTRA_CA_CERTS`, doesn't work with embedded client).
        """
        return __config__.get("extraCaCerts")

    @_builtins.property
    def master_password(self) -> Optional[str]:
        return __config__.get("masterPassword")

    @_builtins.property
    def server(self) -> Optional[str]:
        """
        Bitwarden Server URL (default: `https://vault.bitwarden.com`, env: `BW_URL` or `BWS_SERVER_URL`).
        """
        return __config__.get("server")

    @_builtins.property
    def session_key(self) -> Optional[str]:
        """
        A Bitwarden Session Key (env: `BW_SESSION`)
        """
        return __config__.get("sessionKey")

    @_builtins.property
    def vault_path(self) -> Optional[str]:
        """
        Alternative directory for storing the Vault locally (default: `.bitwarden/`, env: `BITWARDENCLI_APPDATA_DIR`; set to empty string to use CLI default).
        """
        return __config__.get("vaultPath")
