apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lidarr
  namespace: media
spec:
  data:
    - remoteRef:
        key: lidarr
      secretKey: LIDARR__AUTH__APIKEY
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: lidarr-app
        property: password
      secretKey: LIDARR__POSTGRES__PASSWORD
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-media
