apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: obico-ml-api-token
  namespace: printing
spec:
  dataFrom:
    - rewrite:
        - regexp:
            source: password
            target: ML_API_TOKEN
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: obico-ml-api-token
  refreshPolicy: CreatedOnce
