apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: obico
  namespace: printing
spec:
  data:
    - remoteRef:
        key: obico-app
        property: password
      secretKey: DB_PASSWORD
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-printing
    - remoteRef:
        key: printing/obico/ml-api-token
      secretKey: ML_API_TOKEN
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: printing/obico/secret-key
      secretKey: SECRET_KEY
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
