apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: obico-ml-api-token
  namespace: printing
spec:
  allowRepeat: true
  digits: 10
  length: 32
  noUpper: true
  symbols: 0
