apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: syncthing
  namespace: home
spec:
  data:
    - remoteRef:
        key: syncthing/api-key
      secretKey: STGUIAPIKEY
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
