apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--syncthing--syncthing-dst
  namespace: home
spec:
  restic:
    copyMethod: Direct
    destinationPVC: syncthing-state
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--syncthing--syncthing
  trigger:
    manual: "1"
