apiVersion: v1
data:
  nfd-master.conf: |-
    extraLabelNs:
    - nvidia.com
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: nvidia-gpu-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-feature-discovery
  name: nvidia-gpu-operator-node-feature-discovery-master-conf
  namespace: ai
