apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: nvidia-gpu-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-feature-discovery
  name: nvidia-gpu-operator-node-feature-discovery-worker
  namespace: ai
rules:
  - apiGroups:
      - nfd.k8s-sigs.io
    resources:
      - nodefeatures
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
