apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: nvidia-gpu-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-feature-discovery
  name: node-feature-discovery
  namespace: ai
