apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--navidrome--navidrome-dst
  namespace: media
spec:
  restic:
    copyMethod: Direct
    destinationPVC: navidrome
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--navidrome--navidrome
  trigger:
    manual: "1"
