apiVersion: v1
data:
  configuration.yaml: |-
    auth_oidc:
      claims:
        display_name: name
        groups: groups
        username: preferred_username
      client_id: home-assistant
      discovery_url: https://keycloak.trdos.me/realms/default/.well-known/openid-configuration
      display_name: Keycloak SSO
      features:
        automatic_person_creation: true
        automatic_user_linking: true
        force_https: true
      roles:
        admin: admin
    homeassistant:
      external_url: https://hass.trdos.me
      name: Homelab
    http:
      trusted_proxies:
      - 10.0.0.0/8
      - 192.168.50.0/24
      use_x_forwarded_for: true
    logger:
      logs:
        custom_components.auth_oidc: debug
    lovelace:
      mode: storage
      resources:
      - type: module
        url: /local/nixos-lovelace-modules/advanced-camera-card.js
      - type: module
        url: /local/nixos-lovelace-modules/audio-2fcc598a.js
      - type: module
        url: /local/nixos-lovelace-modules/base-735bb1e8.js
      - type: module
        url: /local/nixos-lovelace-modules/card-4a000667.js
      - type: module
        url: /local/nixos-lovelace-modules/date-picker-073737d4.js
      - type: module
        url: /local/nixos-lovelace-modules/dispatch-live-error-f976d960.js
      - type: module
        url: /local/nixos-lovelace-modules/editor-16cf5263.js
      - type: module
        url: /local/nixos-lovelace-modules/endOfDay-1192fb2f.js
      - type: module
        url: /local/nixos-lovelace-modules/engine-86b0096c.js
      - type: module
        url: /local/nixos-lovelace-modules/engine-browse-media-420b94ac.js
      - type: module
        url: /local/nixos-lovelace-modules/engine-frigate-07d19a79.js
      - type: module
        url: /local/nixos-lovelace-modules/engine-generic-cd0d96ce.js
      - type: module
        url: /local/nixos-lovelace-modules/engine-motioneye-7225c43c.js
      - type: module
        url: /local/nixos-lovelace-modules/engine-reolink-b93adb64.js
      - type: module
        url: /local/nixos-lovelace-modules/engine-tplink-1bbdaee4.js
      - type: module
        url: /local/nixos-lovelace-modules/entity-camera-b6c06b0e.js
      - type: module
        url: /local/nixos-lovelace-modules/fireworks-51ec73e7.js
      - type: module
        url: /local/nixos-lovelace-modules/folder-gallery-e8d22e2f.js
      - type: module
        url: /local/nixos-lovelace-modules/frigate-hass-card.js
      - type: module
        url: /local/nixos-lovelace-modules/gallery-core-caef16a6.js
      - type: module
        url: /local/nixos-lovelace-modules/get-technology-for-video-rtc-778a0c05.js
      - type: module
        url: /local/nixos-lovelace-modules/ghost-753da694.js
      - type: module
        url: /local/nixos-lovelace-modules/ha-e25cf40d.js
      - type: module
        url: /local/nixos-lovelace-modules/hearts-c63fb9f5.js
      - type: module
        url: /local/nixos-lovelace-modules/image-4853f590.js
      - type: module
        url: /local/nixos-lovelace-modules/image-51138a0f.js
      - type: module
        url: /local/nixos-lovelace-modules/image-player-eff03df9.js
      - type: module
        url: /local/nixos-lovelace-modules/image-updating-player-02aad9f4.js
      - type: module
        url: /local/nixos-lovelace-modules/index-577b5e61.js
      - type: module
        url: /local/nixos-lovelace-modules/index-5e2b7c1c.js
      - type: module
        url: /local/nixos-lovelace-modules/index-7c5626cf.js
      - type: module
        url: /local/nixos-lovelace-modules/index-a94d25a3.js
      - type: module
        url: /local/nixos-lovelace-modules/jsmpeg-20dd7c29.js
      - type: module
        url: /local/nixos-lovelace-modules/lang-ca-f85ce535.js
      - type: module
        url: /local/nixos-lovelace-modules/lang-de-6dc05ec2.js
      - type: module
        url: /local/nixos-lovelace-modules/lang-fr-163f03e7.js
      - type: module
        url: /local/nixos-lovelace-modules/lang-it-e52e5194.js
      - type: module
        url: /local/nixos-lovelace-modules/lang-pl-375c7c5f.js
      - type: module
        url: /local/nixos-lovelace-modules/lang-pt-BR-78c23b42.js
      - type: module
        url: /local/nixos-lovelace-modules/lang-pt-PT-64e6e903.js
      - type: module
        url: /local/nixos-lovelace-modules/live-provider-1f5bb452.js
      - type: module
        url: /local/nixos-lovelace-modules/media-dimensions-container-ab9a2123.js
      - type: module
        url: /local/nixos-lovelace-modules/media-gallery-6b645558.js
      - type: module
        url: /local/nixos-lovelace-modules/media-grid-29a75ede.js
      - type: module
        url: /local/nixos-lovelace-modules/repeat-97fe1dd7.js
      - type: module
        url: /local/nixos-lovelace-modules/shamrocks-a848b9cd.js
      - type: module
        url: /local/nixos-lovelace-modules/snow-20538f48.js
      - type: module
        url: /local/nixos-lovelace-modules/startOfHour-5d598d49.js
      - type: module
        url: /local/nixos-lovelace-modules/timeline-31c1ae14.js
      - type: module
        url: /local/nixos-lovelace-modules/timeline-core-d90f54fc.js
      - type: module
        url: /local/nixos-lovelace-modules/webrtc-card-6250d7b9.js
      - type: module
        url: /local/nixos-lovelace-modules/zoomer-9791e371.js
      - type: module
        url: /local/nixos-lovelace-modules/apexcharts-card.js
      - type: module
        url: /local/nixos-lovelace-modules/atomic-calendar-revive.js
      - type: module
        url: /local/nixos-lovelace-modules/auto-entities.js
      - type: module
        url: /local/nixos-lovelace-modules/battery-state-card.js
      - type: module
        url: /local/nixos-lovelace-modules/bubble-card.js
      - type: module
        url: /local/nixos-lovelace-modules/bubble-pop-up-fix.js
      - type: module
        url: /local/nixos-lovelace-modules/button-card.js
      - type: module
        url: /local/nixos-lovelace-modules/card-mod.js
      - type: module
        url: /local/nixos-lovelace-modules/clock-weather-card.js
      - type: module
        url: /local/nixos-lovelace-modules/custom-sidebar-plugin.js
      - type: module
        url: /local/nixos-lovelace-modules/custom-sidebar.js
      - type: module
        url: /local/nixos-lovelace-modules/decluttering-card.js
      - type: module
        url: /local/nixos-lovelace-modules/flower-card.js
      - type: module
        url: /local/nixos-lovelace-modules/lovelace-horizon-card.js
      - type: module
        url: /local/nixos-lovelace-modules/hourly-weather.js
      - type: module
        url: /local/nixos-lovelace-modules/kiosk-mode-es5.js
      - type: module
        url: /local/nixos-lovelace-modules/kiosk-mode.js
      - type: module
        url: /local/nixos-lovelace-modules/light-entity-card.js
      - type: module
        url: /local/nixos-lovelace-modules/material-you-utilities.min.js
      - type: module
        url: /local/nixos-lovelace-modules/mini-graph-card-bundle.js
      - type: module
        url: /local/nixos-lovelace-modules/mini-media-player-bundle.js
      - type: module
        url: /local/nixos-lovelace-modules/multiple-entity-row.js
      - type: module
        url: /local/nixos-lovelace-modules/mushroom.js
      - type: module
        url: /local/nixos-lovelace-modules/navbar-card.js
      - type: module
        url: /local/nixos-lovelace-modules/plotly-graph-card.js
      - type: module
        url: /local/nixos-lovelace-modules/restriction-card.js
      - type: module
        url: /local/nixos-lovelace-modules/sankey-chart.js
      - type: module
        url: /local/nixos-lovelace-modules/scheduler-card.js
      - type: module
        url: /local/nixos-lovelace-modules/swipe-navigation.js
      - type: module
        url: /local/nixos-lovelace-modules/template-entity-row.js
      - type: module
        url: /local/nixos-lovelace-modules/universal-remote-card.min.js
      - type: module
        url: /local/nixos-lovelace-modules/versatile-thermostat-ui-card.js
      - type: module
        url: /local/nixos-lovelace-modules/weather-card.js
      - type: module
        url: /local/nixos-lovelace-modules/weather-chart-card.js
      - type: module
        url: /local/nixos-lovelace-modules/zigbee2mqtt-networkmap.js
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: ha
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ha
  name: ha
  namespace: home
