apiVersion: v1
data:
  configuration.yaml: |-
    homeassistant:
      external_url: https://hass.trdos.me
      name: Home
    http:
      trusted_proxies:
      - 10.42.0.0/16
      - 10.43.0.0/16
      use_x_forwarded_for: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: ha
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ha
  name: ha
  namespace: home
