apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ha
  namespace: home
spec:
  data:
    - remoteRef:
        key: ha-app
        property: password
      secretKey: HASS_RECORDER_DB_URL
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-home
    - remoteRef:
        key: ha/admin/password
      secretKey: HASS_ADMIN_PASSWORD
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
  target:
    template:
      data:
        HASS_ADMIN_PASSWORD: '{{ .HASS_ADMIN_PASSWORD }}'
        HASS_RECORDER_DB_URL: postgresql://ha:{{ .HASS_RECORDER_DB_URL }}@ha-rw.home.svc.cluster.local:5432/ha
