apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: generic-device-plugin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: generic-device-plugin
  name: generic-device-plugin
  namespace: kube-system
