apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: cicd
spec:
  destination:
    namespace: tailscale
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./nixidy/generated/prod/tailscale-operator
    repoURL: https://github.com/schradert/millionaire.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
      - PruneLast=true
      - ServerSideApply=true
