apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: crds
  namespace: cicd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./nixidy/generated/prod/crds
    repoURL: https://github.com/schradert/millionaire.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
      - PruneLast=true
      - ServerSideApply=true
