apiVersion: v1
data:
  password: Y2xpY2tob3VzZV9vcGVyYXRvcl9wYXNzd29yZA==
  username: Y2xpY2tob3VzZV9vcGVyYXRvcg==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: clickhouse
    meta.helm.sh/release-namespace: storage
  labels:
    app.kubernetes.io/instance: clickhouse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operator
  name: clickhouse-operator
  namespace: storage
type: Opaque
