apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: clickhouse-operator
  namespace: storage
spec:
  endpoints:
    - port: ch-metrics
    - port: op-metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: clickhouse
      app.kubernetes.io/name: operator
