apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-config
  namespace: kube-system
spec:
  data:
    - remoteRef:
        key: adguard/admin/password-hash
      secretKey: password_hash
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: adguard-config
    template:
      data:
        AdGuardHome.yaml: '{"dns":{"bind_hosts":["0.0.0.0"],"bootstrap_dns":["1.1.1.1","1.0.0.1"],"port":53,"upstream_dns":["[//]192.168.50.1","1.1.1.1","1.0.0.1"]},"http":{"address":"0.0.0.0:3000"},"schema_version":29,"users":[{"name":"admin","password":"{{ .password_hash }}"}]}'
