apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: adguard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: adguard
  name: adguard
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
