apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: baikal
  namespace: home
spec:
  dataFrom:
    - rewrite:
        - regexp:
            source: password
            target: BAIKAL_ADMIN_PASSWORD
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: baikal
  refreshPolicy: CreatedOnce
