apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: baikal
  namespace: home
spec:
  data:
    - remoteRef:
        key: baikal/admin-password
      secretKey: BAIKAL_ADMIN_PASSWORD
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
