apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie
  namespace: health
spec:
  data:
    - remoteRef:
        key: mealie-app
        property: password
      secretKey: db_password.txt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-health
    - remoteRef:
        key: mealie
        property: CLIENT_SECRET
      secretKey: client_secret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
