apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-admin
  namespace: health
spec:
  dataFrom:
    - rewrite:
        - regexp:
            source: password
            target: password
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: mealie-admin
  refreshPolicy: CreatedOnce
