apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: mealie-admin
  namespace: health
spec:
  data:
    - match:
        remoteRef:
          remoteKey: mealie/admin-password
        secretKey: password
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: bitwarden
  selector:
    secret:
      name: mealie-admin
