apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/controller: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
  name: keycloak
  namespace: identity
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: keycloak
      app.kubernetes.io/instance: keycloak
      app.kubernetes.io/name: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: keycloak
        app.kubernetes.io/instance: keycloak
        app.kubernetes.io/name: keycloak
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - start
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://keycloak-rw:5432/keycloak
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_FEATURES
              value: hostname:v2
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: keycloak.trdos.me
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_PROXY_HEADERS
              value: xforwarded
          envFrom:
            - secretRef:
                name: keycloak
          image: quay.io/keycloak/keycloak:26.1
          livenessProbe:
            httpGet:
              path: /health/live
              port: management
          name: keycloak
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9000
              name: management
          readinessProbe:
            httpGet:
              path: /health/ready
              port: management
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /health/started
              port: management
            periodSeconds: 10
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      hostname: keycloak
      serviceAccountName: default
      subdomain: keycloak
