apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak
  namespace: identity
spec:
  data:
    - remoteRef:
        key: keycloak-app
        property: password
      secretKey: db_password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
    - remoteRef:
        key: keycloak/admin/password
      secretKey: admin_password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    template:
      data:
        KC_BOOTSTRAP_ADMIN_PASSWORD: '{{ .admin_password }}'
        KC_BOOTSTRAP_ADMIN_USERNAME: admin
        KC_DB_PASSWORD: '{{ .db_password }}'
