apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  name: keycloak-auth
  namespace: identity
spec:
  activeDeadlineSeconds: 1200
  backoffLimit: 6
  template:
    spec:
      containers:
        - command:
            - /bin/bash
            - /config/users.sh
          env:
            - name: KEYCLOAK_URL
              value: http://keycloak.identity.svc.cluster.local:8080
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  key: KC_BOOTSTRAP_ADMIN_USERNAME
                  name: keycloak
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KC_BOOTSTRAP_ADMIN_PASSWORD
                  name: keycloak
          image: quay.io/keycloak/keycloak:26.1.5@sha256:be6a86215213145bfb4fb3e2b3ab982a806d00262655abdcf3ffa6a38d241c7c
          name: users
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /config
              name: config
              readOnly: true
            - mountPath: /secrets/initial
              name: initial
              readOnly: true
            - mountPath: /tmp
              name: tmp
      initContainers:
        - env:
            - name: KEYCLOAK_URL
              value: http://keycloak.identity.svc.cluster.local:8080
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  key: KC_BOOTSTRAP_ADMIN_USERNAME
                  name: keycloak
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KC_BOOTSTRAP_ADMIN_PASSWORD
                  name: keycloak
            - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
              value: "true"
            - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
              value: 300s
            - name: IMPORT_FILES_LOCATIONS
              value: /config/*.json
            - name: IMPORT_CACHE_ENABLED
              value: "false"
            - name: JAVA_TOOL_OPTIONS
              value: -Djava.io.tmpdir=/tmp
          image: docker.io/adorsys/keycloak-config-cli:6.5.1-26.1.0@sha256:1b22dfaa9ae0c71f74b0342f9221a6510f272da5def683dbba26a98e6b1b1411
          name: flows
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /config
              name: config
              readOnly: true
            - mountPath: /tmp
              name: tmp
      restartPolicy: OnFailure
      securityContext:
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - configMap:
            name: keycloak-auth
          name: config
        - name: initial
          secret:
            secretName: keycloak-initial-password
        - emptyDir: {}
          name: tmp
