apiVersion: keycloak.hostzero.com/v1beta1
kind: KeycloakUser
metadata:
  name: tristan
  namespace: identity
spec:
  definition:
    email: t0rdos@pm.me
    emailVerified: true
    enabled: true
    groups:
      - admin
      - family
    username: tristan
  realmRef:
    name: default
