apiVersion: keycloak.hostzero.com/v1beta1
kind: KeycloakRealm
metadata:
  name: default
  namespace: identity
spec:
  definition:
    accessTokenLifespan: 250
    bruteForceProtected: true
    displayName: Default
    duplicateEmailsAllowed: false
    enabled: true
    loginWithEmailAllowed: true
    otpPolicyType: totp
    realm: default
    registrationAllowed: false
    smtpServer:
      auth: "false"
      from: noreply@trdos.me
      fromDisplayName: Homelab
      host: stalwart.mail.svc.cluster.local
      port: "25"
      ssl: "false"
      starttls: "false"
    ssoSessionIdleTimeout: 86400
    ssoSessionMaxLifespan: 259200
    webAuthnPolicyRpEntityName: Homelab Default Realm
    webAuthnPolicyRpId: trdos.me
  instanceRef:
    name: default
