apiVersion: keycloak.hostzero.com/v1beta1
kind: KeycloakInstance
metadata:
  name: default
  namespace: identity
spec:
  baseUrl: http://keycloak.identity.svc.cluster.local:8080
  credentials:
    secretRef:
      name: keycloak
      passwordKey: KC_BOOTSTRAP_ADMIN_PASSWORD
      usernameKey: KC_BOOTSTRAP_ADMIN_USERNAME
