apiVersion: keycloak.hostzero.com/v1beta1
kind: KeycloakClient
metadata:
  name: immich
  namespace: identity
spec:
  clientSecretRef:
    create: true
    name: immich
  definition:
    clientId: immich
    defaultClientScopes:
      - openid
      - profile
      - email
      - groups
    directAccessGrantsEnabled: false
    enabled: true
    name: Immich
    protocol: openid-connect
    protocolMappers:
      - config:
          access.token.claim: "true"
          aggregate.attrs: "true"
          claim.name: immich_role
          id.token.claim: "true"
          introspection.token.claim: "true"
          jsonType.label: String
          multivalued: "false"
          user.attribute: immich_role
          userinfo.token.claim: "true"
        consentRequired: false
        name: immich_role
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
    publicClient: false
    redirectUris:
      - https://immich.trdos.me/auth/login
      - https://immich.trdos.me/user-settings
      - app.immich:///oauth-callback
    standardFlowEnabled: true
    webOrigins:
      - https://immich.trdos.me
  realmRef:
    name: default
