apiVersion: keycloak.hostzero.com/v1beta1
kind: KeycloakClient
metadata:
  name: librechat
  namespace: identity
spec:
  clientSecretRef:
    create: true
    name: librechat
  definition:
    clientId: librechat
    defaultClientScopes:
      - openid
      - profile
      - email
      - groups
    directAccessGrantsEnabled: false
    enabled: true
    name: LibreChat
    protocol: openid-connect
    publicClient: false
    redirectUris:
      - https://chat.trdos.me/oauth/openid/callback
    standardFlowEnabled: true
    webOrigins:
      - https://chat.trdos.me
  realmRef:
    name: default
