apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: keycloak-initial-password
  namespace: identity
spec:
  data:
    - match:
        remoteRef:
          remoteKey: keycloak/tristan/initial-password
        secretKey: password
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: bitwarden
  selector:
    secret:
      name: keycloak-initial-password
