apiVersion: v1
data:
  settings.json: '{"zwave":{"enabled":true,"port":"/dev/serial/by-id/usb-Nabu_Casa_ZWA-2_1CDBD4AEBC68-if00"}}'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: zwave-js-ui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zwave-js-ui
  name: zwave-js-ui
  namespace: home
