apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: zwave-js-ui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zwave-js-ui
  name: zwave-js-ui
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
