apiVersion: v1
data:
  webdav.yml: '{"address":"0.0.0.0","directory":"/data","noauth":true,"permissions":"CRUD","port":8080,"prefix":"/"}'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: webdav
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webdav
  name: webdav
  namespace: home
