apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: webdav
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webdav
  name: webdav
  namespace: home
