apiVersion: v1
data:
  keto.yaml: |
    namespaces:
    - id: 0
      name: apps
    - id: 1
      name: groups
    serve:
      metrics:
        port: 4468
      read:
        port: 4466
      write:
        port: 4467
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: keto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keto
  name: keto-config
  namespace: identity
