apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keto
  namespace: identity
spec:
  data:
    - remoteRef:
        key: keto-app
        property: password
      secretKey: db_password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
