apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test-success
  labels:
    app.kubernetes.io/instance: keto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keto
  name: keto-test-connection
  namespace: identity
spec:
  containers:
    - args:
        - keto-write:80/health/ready
      command:
        - wget
      image: busybox:1
      name: wget
  restartPolicy: Never
