apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: read
    app.kubernetes.io/instance: keto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keto
    service.ory.sh/type: headless
  name: keto-read-headless
  namespace: identity
spec:
  clusterIP: None
  ports:
    - appProtocol: grpc
      name: grpc-read
      port: 4466
      protocol: TCP
      targetPort: grpc-read
  selector:
    app.kubernetes.io/instance: keto
    app.kubernetes.io/name: keto
  type: ClusterIP
