apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: write
    app.kubernetes.io/instance: keto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keto
  name: keto-write
  namespace: identity
spec:
  ports:
    - appProtocol: grpc
      name: grpc-write
      port: 80
      protocol: TCP
      targetPort: grpc-write
  selector:
    app.kubernetes.io/instance: keto
    app.kubernetes.io/name: keto
  type: ClusterIP
