apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  data:
    - remoteRef:
        key: headscale/preauth-key/k8s
      secretKey: authkey
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: tailscale-operator
    template:
      data:
        TS_AUTHKEY: '{{ .authkey }}'
