apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: heretic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: heretic
  name: heretic-output
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-block
