apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: heretic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: heretic
  name: heretic
  namespace: ai
