apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: mainsail
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mainsail
  name: mainsail
  namespace: printing
