apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw
  namespace: ai-sandbox
spec:
  data:
    - remoteRef:
        key: ai/openclaw/discord-token
      secretKey: DISCORD_BOT_TOKEN
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
