apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: openclaw
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: openclaw
  name: openclaw
  namespace: ai-sandbox
