apiVersion: v1
data:
  chirpstack.toml: |-
    [logging]
      level="info"

    [postgresql]
      dsn="postgres://chirpstack:$CHIRPSTACK_DB_PASSWORD@chirpstack-rw.home.svc.cluster.local:5432/chirpstack?sslmode=disable"
      max_open_connections=10

    [redis]
      servers=["redis://chirpstack-dragonfly.home.svc.cluster.local:6379/"]

    [network]
      enabled_regions=["us915_0"]

    [integration]
      enabled=["mqtt"]

    [integration.mqtt]
      server="tcp://mosquitto.home.svc.cluster.local:1883/"

    [api]
      bind="0.0.0.0:8080"

    [user_authentication.openid_connect]
      enabled=true
      registration_enabled=true
      registration_callback_url="https://chirpstack.trdos.me/api/oauth2/callback"
      provider_url="https://keycloak.trdos.me/realms/default"
      client_id="$CHIRPSTACK_OIDC_CLIENT_ID"
      client_secret="$CHIRPSTACK_OIDC_CLIENT_SECRET"
      redirect_url="https://chirpstack.trdos.me/api/oauth2/callback"
      login_label="Login with SSO"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: chirpstack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: chirpstack
  name: chirpstack
  namespace: home
