apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/controller: chirpstack
    app.kubernetes.io/instance: chirpstack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: chirpstack
  name: chirpstack
  namespace: home
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: chirpstack
      app.kubernetes.io/instance: chirpstack
      app.kubernetes.io/name: chirpstack
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/configMaps: c438b254c896f464c928f29c606b60222c27a4c0b6f5d8af5f82f06616d16dd4
      labels:
        app.kubernetes.io/controller: chirpstack
        app.kubernetes.io/instance: chirpstack
        app.kubernetes.io/name: chirpstack
    spec:
      automountServiceAccountToken: false
      containers:
        - args:
            - -c
            - /etc/chirpstack
          envFrom:
            - secretRef:
                name: chirpstack
          image: chirpstack/chirpstack:4@sha256:cecb45bd2dfc9de55d32c620d6674093f859a899f4de36eb82924c7aa3bda8de
          livenessProbe:
            tcpSocket:
              port: 8080
          name: chirpstack
          readinessProbe:
            tcpSocket:
              port: 8080
          startupProbe:
            tcpSocket:
              port: 8080
          volumeMounts:
            - mountPath: /etc/chirpstack/chirpstack.toml
              name: config
              readOnly: true
              subPath: chirpstack.toml
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      serviceAccountName: chirpstack
      volumes:
        - configMap:
            name: chirpstack
          name: config
