apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chirpstack
  namespace: home
spec:
  data:
    - remoteRef:
        key: chirpstack-app
        property: password
      secretKey: CHIRPSTACK_DB_PASSWORD
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-home
    - remoteRef:
        key: chirpstack
        property: client-id
      secretKey: CHIRPSTACK_OIDC_CLIENT_ID
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
    - remoteRef:
        key: chirpstack
        property: client-secret
      secretKey: CHIRPSTACK_OIDC_CLIENT_SECRET
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
