apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-admin
  namespace: media
spec:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: jellyfin-admin
  refreshPolicy: CreatedOnce
