apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: jellyfin-admin
  namespace: media
spec:
  allowRepeat: true
  digits: 10
  length: 32
  noUpper: false
  symbols: 0
