apiVersion: v1
data:
  .env: |-
    AUTHENTICATION_GUARD=remote_user_guard
    AUTHENTICATION_GUARD_HEADER=HTTP_X_AUTH_REQUEST_PREFERRED_USERNAME
    AUTHENTICATION_GUARD_EMAIL=HTTP_X_AUTH_REQUEST_EMAIL
    DB_CONNECTION=pgsql
    DB_HOST=firefly-rw
    DB_PORT=5432
    DB_DATABASE=firefly
    DB_USERNAME=firefly
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: firefly
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: firefly
  name: firefly
  namespace: finance
