apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly
  namespace: finance
spec:
  data:
    - remoteRef:
        key: firefly/app_key
      secretKey: app_key.txt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: firefly-app
        property: password
      secretKey: db_password.txt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-finance
