apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: firefly
  namespace: finance
spec:
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  errors:
    - handler: redirect
  match:
    methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
    url: https://firefly.trdos.me/<**>
  mutators:
    - handler: header
  upstream:
    url: http://firefly.finance.svc.cluster.local:8080
