passwords:
    age: ENC[AES256_GCM,data:qANs7vXtWGz6qW2YYJITPopDcH83oEDcBfC6EdQ0i6gifI0i2qwB8lzc83x/aS07mvnXgfL64yM8mFKRAyUw1cRTgfLos4NrnTw=,iv:C0l3SAvQromRC2Irqx6c0R5IKyGTpMOFI0zeU2qPpI8=,tag:0QDNaGk/h+968AWcG/xKdA==,type:str]
    k8s-token: ENC[AES256_GCM,data:UjtkQ3mIcpzzE/EhoqMdvwBRY3idLkcQ,iv:sFMHjGZaFPIL7Vz1E/67bQ82ExxUMEq80opiq0PB5ik=,tag:KGqZrceSAN3/ZHwFOb3TSw==,type:str]
bitwarden: ENC[AES256_GCM,data:8VpTptPmqeLS5g6T2QankfBGe4f/efWOmDfsdO3Sa2z74RgtUosmWL1ILUu565Gcl8jWcYYqKMQSs0LS/jsuHnBdTr3aQeJxqBiClIeCTGUdsno1A15wNJpKpQZ6aw==,iv:LNJm4AIAnx1QZqERV2B4KHfkq074X9JBnJ/8JOybs1A=,tag:7nDVYQDL2R0+u1ZPj9Lnkw==,type:str]
sops:
    age:
        - recipient: age15g8wd8rqnz4rxdxcz7jlrm3yqlfj6jqeru5m3xrjhzp0fn2r4v8sd5ehh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WmEzQTd2UDdxdjV1bzN5
            TU5iaFNGb0lWdmJVdkpaRU55cXg0K094RHk0ClF5TDdxbFZCYlBvelIyeTlZekh5
            QkxuYzNVcVZxNCtoWk9WdVpON0N2ZzgKLS0tICtjRHZVTlRQWWdPZm9CMkZsVC9m
            R3M4MnlobFpXZ2Z2UkNad2RyemgxRXMKUw/FBGsByl/8KoYm5z+S1+eTEm8NtMfw
            5uasqiCE8rS6foY/b8Z7QRqncn+ZsIJ/Z7dtnx2sD3xi/9PS7vbK8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kr4my68wnc3en2ajhcwj26ffk3tgdlrx9uknjxrlvjf76lw5h4kqyslt62
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY1d2TmxSTVlUVHVkLzRl
            cUtVVS9PK20yL2NGYjIxamtNNm5QLzJuWm0wCjdEZ3BqOFhVRWVFTmhVOHhIQU5M
            cnNybFpXZlJ1Ry9RYTZ1cDUxOHh2UmsKLS0tIEkxbXp3UjRoVGhqclZaek5RZElr
            S3grRlJnelJ3OG8xUi8rWVlkaTdXUlkKocOXAgphdFC139FeG+TZC/CYFBHaoHKL
            KQWlFzSYB6mbPAEbhVa4u/LBCHQ9jdg+6ftbTo2QVmtZfesV3gr9bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T08:11:13Z"
    mac: ENC[AES256_GCM,data:GoN663daM4CesPKRKL++Wz27uXGjSinvtp+nkikrNxO1yrHrxnvJBl+Ow1SE2ZRm7+XlA0O7pU0wmfIs8rcZWpLhy30rVO+aMA7b8t9cK6jJuQ8SbS1omp2pLEoG7DlBWDDyf0Sq2/U5/JJqHIlNTvg5C1Lftoy0GmZj2SHx8g4=,iv:PLIkuMQbtQ1/VrhVb8zyWctMSkS1S8ptPQwRp8HxTHQ=,tag:8hGZ35PWiX8ClNAKDaKSSg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
