passwords:
    age: ENC[AES256_GCM,data:qANs7vXtWGz6qW2YYJITPopDcH83oEDcBfC6EdQ0i6gifI0i2qwB8lzc83x/aS07mvnXgfL64yM8mFKRAyUw1cRTgfLos4NrnTw=,iv:C0l3SAvQromRC2Irqx6c0R5IKyGTpMOFI0zeU2qPpI8=,tag:0QDNaGk/h+968AWcG/xKdA==,type:str]
    k8s-token: ENC[AES256_GCM,data:UjtkQ3mIcpzzE/EhoqMdvwBRY3idLkcQ,iv:sFMHjGZaFPIL7Vz1E/67bQ82ExxUMEq80opiq0PB5ik=,tag:KGqZrceSAN3/ZHwFOb3TSw==,type:str]
sops:
    age:
        - recipient: age15g8wd8rqnz4rxdxcz7jlrm3yqlfj6jqeru5m3xrjhzp0fn2r4v8sd5ehh3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WmEzQTd2UDdxdjV1bzN5
            TU5iaFNGb0lWdmJVdkpaRU55cXg0K094RHk0ClF5TDdxbFZCYlBvelIyeTlZekh5
            QkxuYzNVcVZxNCtoWk9WdVpON0N2ZzgKLS0tICtjRHZVTlRQWWdPZm9CMkZsVC9m
            R3M4MnlobFpXZ2Z2UkNad2RyemgxRXMKUw/FBGsByl/8KoYm5z+S1+eTEm8NtMfw
            5uasqiCE8rS6foY/b8Z7QRqncn+ZsIJ/Z7dtnx2sD3xi/9PS7vbK8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kr4my68wnc3en2ajhcwj26ffk3tgdlrx9uknjxrlvjf76lw5h4kqyslt62
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY1d2TmxSTVlUVHVkLzRl
            cUtVVS9PK20yL2NGYjIxamtNNm5QLzJuWm0wCjdEZ3BqOFhVRWVFTmhVOHhIQU5M
            cnNybFpXZlJ1Ry9RYTZ1cDUxOHh2UmsKLS0tIEkxbXp3UjRoVGhqclZaek5RZElr
            S3grRlJnelJ3OG8xUi8rWVlkaTdXUlkKocOXAgphdFC139FeG+TZC/CYFBHaoHKL
            KQWlFzSYB6mbPAEbhVa4u/LBCHQ9jdg+6ftbTo2QVmtZfesV3gr9bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T08:29:39Z"
    mac: ENC[AES256_GCM,data:e/gbwnyKv1FVBkvor7xD0qGoNJzwyPQcvO1vB9ZsEC4bPx6IMQUVPY7ybX4icWnGgk6C0ImRJfaJ5VyJWwIXsFyWZjlH195VAjQeKF5/H/gI8Hxt7dIxWY3E7wfvNpPn3iYrRX1jeQQgtukUr9zhv8oOBvFm0UNjrKRBK7BMT38=,iv:cDk2HvFEVErMnknpEYhPRMwlyBCgYhYH/tk5qn5FY/w=,tag:1SqddjFRVvkMgpfZ2yJmLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
