apiVersion: v1
data:
  APP_DOMAIN: sure.trdos.me
  DB_HOST: sure-rw
  DB_PORT: "5432"
  OIDC_ISSUER: https://hydra.trdos.me
  OIDC_REDIRECT_URI: https://sure.trdos.me/auth/oidc/callback
  ONBOARDING_STATE: invite_only
  POSTGRES_USER: sure
  RAILS_ASSUME_SSL: "true"
  RAILS_ENV: production
  REDIS_URL: redis://sure-dragonfly.finance.svc.cluster.local:6379/0
  SELF_HOSTED: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: sure
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sure
  name: sure
  namespace: finance
