apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: sure-dragonfly
  namespace: finance
spec:
  args:
    - --proactor_threads
    - "2"
  replicas: 1
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 256Mi
