apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sure
  namespace: finance
spec:
  data:
    - remoteRef:
        key: sure/secret_key_base
      secretKey: SECRET_KEY_BASE
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: sure-app
        property: password
      secretKey: POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-finance
    - remoteRef:
        key: sure
        property: client-id
      secretKey: OIDC_CLIENT_ID
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
    - remoteRef:
        key: sure
        property: client-secret
      secretKey: OIDC_CLIENT_SECRET
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
