apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maloja
  namespace: media
spec:
  data:
    - remoteRef:
        key: maloja/admin-password
      secretKey: admin_password
    - remoteRef:
        key: listenbrainz-pseudonymous
        property: token
      secretKey: listenbrainz_token
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    template:
      data:
        MALOJA_FORCE_PASSWORD: '{{ .admin_password }}'
        MALOJA_SCROBBLE_LASTFM_KEY: ""
        MALOJA_SCROBBLE_LASTFM_SECRET: ""
        MALOJA_SCROBBLE_LISTENBRAINZ_TOKEN: '{{ .listenbrainz_token }}'
