apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maloja
  namespace: media
spec:
  data:
    - remoteRef:
        key: maloja-admin
        property: password
      secretKey: admin_password
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-media
  target:
    template:
      data:
        MALOJA_FORCE_PASSWORD: '{{ .admin_password }}'
