apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: maloja-admin
  namespace: media
spec:
  data:
    - match:
        remoteRef:
          remoteKey: maloja/admin-password
        secretKey: password
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: bitwarden
  selector:
    secret:
      name: maloja-admin
