apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: maloja
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: maloja
  name: maloja
  namespace: media
