apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: windmill-admin
  namespace: development
spec:
  data:
    - remoteRef:
        key: windmill/admin/password
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
