apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: windmill-db
  namespace: development
spec:
  data:
    - remoteRef:
        key: windmill-app
        property: password
      secretKey: password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-development
  target:
    template:
      data:
        DATABASE_URL: postgresql://windmill:{{ .password }}@windmill-rw.development.svc.cluster.local:5432/windmill?sslmode=disable
