apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: org-files
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-filesystem
