apiVersion: v1
data:
  config.yaml: |
    access_rules:
      repositories:
      - file:///etc/rules/access-rules.json
    authenticators:
      anonymous:
        enabled: true
      cookie_session:
        config:
          check_session_url: http://oauth2-proxy.identity.svc.cluster.local:4180/oauth2/auth
          extra_from: '@this'
          only:
          - _oauth2_proxy
          preserve_path: true
          subject_from: email
        enabled: true
      noop:
        enabled: true
    authorizers:
      allow:
        enabled: true
      deny:
        enabled: true
    errors:
      handlers:
        json:
          config:
            verbose: false
          enabled: true
        redirect:
          config:
            return_to_query_param: rd
            to: https://oauth2.trdos.me/oauth2/start
            when:
            - error:
              - unauthorized
              - forbidden
              request:
                header:
                  accept:
                  - text/html
          enabled: true
    mutators:
      header:
        config:
          headers:
            X-Auth-Request-Email: '{{ print .Subject }}'
            X-Auth-Request-Preferred-Username: '{{ print .Subject }}'
            X-User-Email: '{{ print .Subject }}'
            X-User-Id: '{{ print .Subject }}'
        enabled: true
      id_token:
        config:
          issuer_url: https://oathkeeper.trdos.me
          jwks_url: file:///etc/oathkeeper/id_token.jwks.json
        enabled: true
      noop:
        enabled: true
    serve:
      api:
        port: 4456
      prometheus:
        port: 9000
      proxy:
        port: 4455
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: oathkeeper
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: oathkeeper
  name: oathkeeper-config
  namespace: identity
