apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oathkeeper-jwks
  namespace: identity
spec:
  data:
    - remoteRef:
        key: ory/oathkeeper/mutator-id-token-jwks
      secretKey: jwks.json
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
