apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test-success
  labels:
    app.kubernetes.io/instance: oathkeeper
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: oathkeeper
  name: oathkeeper-test-connection
  namespace: identity
spec:
  containers:
    - args:
        - http://oathkeeper-api:4456/health/alive
      command:
        - wget
      image: busybox:1
      name: liveness-probe
    - args:
        - http://oathkeeper-api:4456/health/ready
      command:
        - wget
      image: busybox:1
      name: readiness-probe
  restartPolicy: Never
