apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: oathkeeper
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: oathkeeper
  name: oathkeeper-api
  namespace: identity
spec:
  ports:
    - name: http
      port: 4456
      protocol: TCP
      targetPort: http-api
  selector:
    app.kubernetes.io/instance: oathkeeper
    app.kubernetes.io/name: oathkeeper
  type: ClusterIP
