apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: harbor-dragonfly
  namespace: cicd
spec:
  args:
    - --proactor_threads
    - "2"
  replicas: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
