apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-credentials
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: harbor/registry/password
      secretKey: password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: harbor/registry/htpasswd
      secretKey: htpasswd
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
  target:
    template:
      data:
        REGISTRY_HTPASSWD: '{{ .htpasswd }}'
        REGISTRY_PASSWD: '{{ .password }}'
