apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-oidc
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: harbor
        property: client-secret
      secretKey: OIDC_CLIENT_SECRET
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
