apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-oidc
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: harbor
        property: CLIENT_SECRET
      secretKey: clientSecret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
  target:
    template:
      data:
        OIDC_CLIENT_SECRET: '{{ .clientSecret }}'
