apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-robot
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: harbor/robot/secret
      secretKey: secret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
  target:
    template:
      data:
        ROBOT_SECRET: '{{ .secret }}'
