apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: harbor/core/secret
      secretKey: secret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: harbor/core/csrf-key
      secretKey: csrf_key
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: harbor/core/tls-cert
      secretKey: tls_cert
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: harbor/core/tls-key
      secretKey: tls_key
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
  target:
    template:
      data:
        CSRF_KEY: '{{ .csrf_key }}'
        secret: '{{ .secret }}'
        tls.crt: '{{ .tls_cert | b64dec }}'
        tls.key: '{{ .tls_key | b64dec }}'
