apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: harbor/registry/http-secret
      secretKey: http_secret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
  target:
    template:
      data:
        REGISTRY_HTTP_SECRET: '{{ .http_secret }}'
