apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: harbor/admin/password
      secretKey: admin_password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: harbor/secret-key
      secretKey: secret_key
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: harbor-app
        property: password
      secretKey: db_password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-cicd
  target:
    template:
      data:
        HARBOR_ADMIN_PASSWORD: '{{ .admin_password }}'
        password: '{{ .db_password }}'
        secretKey: '{{ .secret_key }}'
