apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  namespace: cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-block
