apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: volsync--harbor--harbor-registry-src
  namespace: cicd
spec:
  restic:
    copyMethod: Direct
    moverSecurityContext:
      fsGroup: 101
    pruneIntervalDays: 8
    repository: volsync--harbor--harbor-registry
    retain:
      daily: 1
      monthly: 1
      weekly: 1
      yearly: 1
  sourcePVC: harbor-registry
  trigger:
    schedule: 0 4 * * *
