apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: promptfoo
  namespace: ai
spec:
  data:
    - remoteRef:
        key: ai/anthropic/api-key
      secretKey: anthropic_key
    - remoteRef:
        key: ai/openai/api-key
      secretKey: openai_key
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    template:
      data:
        ANTHROPIC_API_KEY: '{{ .anthropic_key }}'
        OPENAI_API_KEY: '{{ .openai_key }}'
