apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kratos-ui
  namespace: identity
spec:
  data:
    - remoteRef:
        key: ory/ui/cookie-secret
      secretKey: cookie_secret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: ory/ui/csrf-secret
      secretKey: csrf_secret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
