apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: siyuan
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: siyuan
  name: siyuan
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
