apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--siyuan--siyuan-dst
  namespace: home
spec:
  restic:
    copyMethod: Direct
    destinationPVC: siyuan
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--siyuan--siyuan
  trigger:
    manual: "1"
