apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: siyuan
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: siyuan
    app.kubernetes.io/service: siyuan
  name: siyuan
  namespace: home
spec:
  ports:
    - name: http
      port: 6806
      protocol: TCP
      targetPort: 6806
  selector:
    app.kubernetes.io/controller: siyuan
    app.kubernetes.io/instance: siyuan
    app.kubernetes.io/name: siyuan
  type: ClusterIP
