apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vllm
  namespace: ai
spec:
  data:
    - remoteRef:
        key: ai/huggingface/token
      secretKey: hf_token
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
