apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: contextforge-auth-encryption
  namespace: ai
spec:
  dataFrom:
    - rewrite:
        - regexp:
            source: password
            target: AUTH_ENCRYPTION_SECRET
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: contextforge-auth-encryption
  refreshPolicy: CreatedOnce
