apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: contextforge-default-user
  namespace: ai
spec:
  dataFrom:
    - rewrite:
        - regexp:
            source: password
            target: DEFAULT_USER_PASSWORD
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: contextforge-default-user
  refreshPolicy: CreatedOnce
