apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: contextforge-auth-encryption
  namespace: ai
spec:
  allowRepeat: true
  digits: 10
  length: 32
  noUpper: true
  symbols: 0
