apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: contextforge-default-user
  namespace: ai
spec:
  allowRepeat: true
  digits: 10
  length: 24
  noUpper: true
  symbols: 0
