apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: govee2mqtt
  namespace: home
spec:
  data:
    - remoteRef:
        key: govee/email
      secretKey: email
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: govee/password
      secretKey: password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: govee/api-key
      secretKey: api_key
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
  target:
    template:
      data:
        GOVEE_API_KEY: '{{ .api_key }}'
        GOVEE_EMAIL: '{{ .email }}'
        GOVEE_PASSWORD: '{{ .password }}'
