apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: volsync--govee2mqtt--govee2mqtt-src
  namespace: home
spec:
  restic:
    copyMethod: Direct
    moverSecurityContext:
      fsGroup: 101
    pruneIntervalDays: 8
    repository: volsync--govee2mqtt--govee2mqtt
    retain:
      daily: 1
      monthly: 1
      weekly: 1
      yearly: 1
  sourcePVC: govee2mqtt
  trigger:
    schedule: 0 4 * * *
