apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/controller: openviking
    app.kubernetes.io/instance: openviking
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: openviking
  name: openviking
  namespace: ai
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: openviking
      app.kubernetes.io/instance: openviking
      app.kubernetes.io/name: openviking
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/configMaps: 72c21a2b3366d63fa4eb3bcc9354f33e2cdf7956c0634ff1e55969d021f41c3d
      labels:
        app.kubernetes.io/controller: openviking
        app.kubernetes.io/instance: openviking
        app.kubernetes.io/name: openviking
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: OPENVIKING_SERVER_PORT
              value: "1933"
            - name: OPENVIKING_WITH_BOT
              value: "0"
          envFrom:
            - secretRef:
                name: openviking-root-api-key
          image: ghcr.io/volcengine/openviking:v0.5.0@sha256:c60a83cd79cfce80db5266acb8bdd0908eee8abe8ff559a5f786aa504c251ccf
          livenessProbe:
            httpGet:
              path: /health
              port: http
          name: openviking
          ports:
            - containerPort: 1933
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: 250m
              memory: 1Gi
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
          volumeMounts:
            - mountPath: /app/.openviking/ov.conf
              name: config
              readOnly: true
              subPath: ov.conf
            - mountPath: /app/.openviking
              name: data
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      serviceAccountName: openviking
      volumes:
        - configMap:
            name: openviking
          name: config
        - name: data
          persistentVolumeClaim:
            claimName: openviking
