apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openviking-root-api-key
  namespace: ai
spec:
  dataFrom:
    - rewrite:
        - regexp:
            source: password
            target: OPENVIKING_ROOT_API_KEY
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: openviking-root-api-key
  refreshPolicy: CreatedOnce
