apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: openviking
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: openviking
    app.kubernetes.io/service: openviking
  name: openviking
  namespace: ai
spec:
  ports:
    - name: http
      port: 1933
      protocol: TCP
      targetPort: 1933
  selector:
    app.kubernetes.io/controller: openviking
    app.kubernetes.io/instance: openviking
    app.kubernetes.io/name: openviking
  type: ClusterIP
