apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/controller: oauth2-proxy
    app.kubernetes.io/instance: oauth2-proxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: oauth2-proxy
  name: oauth2-proxy
  namespace: identity
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: oauth2-proxy
      app.kubernetes.io/instance: oauth2-proxy
      app.kubernetes.io/name: oauth2-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/configMaps: d730db4ca0c89b2b661a5be86c2e319081dcf1bdd67ec720122a0e467b65f220
      labels:
        app.kubernetes.io/controller: oauth2-proxy
        app.kubernetes.io/instance: oauth2-proxy
        app.kubernetes.io/name: oauth2-proxy
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - --http-address=0.0.0.0:4180
            - --provider=keycloak-oidc
            - --oidc-issuer-url=https://keycloak.trdos.me/realms/default
            - --client-id=oauth2-proxy
            - --redirect-url=https://oauth2.trdos.me/oauth2/callback
            - --cookie-domain=.trdos.me
            - --cookie-secure=true
            - --cookie-samesite=lax
            - --cookie-name=_oauth2_proxy
            - --email-domain=*
            - --set-xauthrequest=true
            - --upstream=http://localhost:8080/
            - --skip-provider-button=true
            - --reverse-proxy=true
            - --pass-host-header=true
            - --whitelist-domain=.trdos.me
            - --session-store-type=redis
            - --redis-connection-url=redis://oauth2-proxy-dragonfly.identity.svc.cluster.local:6379
          envFrom:
            - secretRef:
                name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.8.1
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              name: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          startupProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 4180
            timeoutSeconds: 1
        - image: nginx:1.27-alpine
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 4180
            timeoutSeconds: 1
          name: router
          ports:
            - containerPort: 8080
              name: router
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 4180
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: 4180
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: routes
              readOnly: true
              subPath: default.conf
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      serviceAccountName: default
      volumes:
        - configMap:
            name: oauth2-proxy
          name: routes
