apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: hydra
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hydra-maester
  name: hydra-hydra-maester
  namespace: identity
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/instance: hydra
      app.kubernetes.io/name: hydra-hydra-maester
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: hydra
        app.kubernetes.io/name: hydra-hydra-maester
        control-plane: controller-manager
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - --metrics-addr=127.0.0.1:8080
            - --hydra-url=http://hydra-admin
            - --hydra-port=4445
            - --endpoint=/admin/clients
          command:
            - /manager
          image: oryd/hydra-maester:v0.0.40
          imagePullPolicy: IfNotPresent
          name: hydra-maester
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seLinuxOptions:
              level: s0:c123,c456
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: hydra-hydra-maester-account
      terminationGracePeriodSeconds: 60
