apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hydra
  namespace: identity
spec:
  data:
    - remoteRef:
        key: ory/hydra/system-secret
      secretKey: system_secret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: ory/hydra/oidc-subject-salt
      secretKey: oidc_salt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: hydra-app
        property: password
      secretKey: db_password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
  target:
    template:
      data:
        db_password: '{{ .db_password }}'
        dsn: postgres://hydra:{{ .db_password }}@hydra-rw.identity.svc.cluster.local:5432/hydra?sslmode=disable
        oidc_salt: '{{ .oidc_salt }}'
        secretsCookie: '{{ .system_secret }}'
        secretsSystem: '{{ .system_secret }}'
        system_secret: '{{ .system_secret }}'
