apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hydra
  namespace: identity
spec:
  data:
    - remoteRef:
        key: ory/hydra/system-secret
      secretKey: system_secret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: ory/hydra/oidc-subject-salt
      secretKey: oidc_salt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: hydra-app
        property: password
      secretKey: db_password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
