apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test-success
  labels:
    app.kubernetes.io/instance: hydra
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hydra
  name: hydra-test-connection
  namespace: identity
spec:
  containers:
    - args:
        - hydra-admin:4445/health/ready
      command:
        - wget
      image: busybox:1
      name: healthcheck-ready
  restartPolicy: Never
