apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hydra-hydra-maester-role-binding
  namespace: identity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hydra-hydra-maester-role
subjects:
  - kind: ServiceAccount
    name: hydra-hydra-maester-account
    namespace: identity
