apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: admin
    app.kubernetes.io/instance: hydra
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hydra
  name: hydra-admin
  namespace: identity
spec:
  ports:
    - name: http
      port: 4445
      protocol: TCP
      targetPort: http-admin
  selector:
    app.kubernetes.io/instance: hydra
    app.kubernetes.io/name: hydra
  type: ClusterIP
