apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-oidc
  namespace: development
spec:
  data:
    - remoteRef:
        key: forgejo
        property: CLIENT_ID
      secretKey: clientId
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
    - remoteRef:
        key: forgejo
        property: CLIENT_SECRET
      secretKey: clientSecret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
  target:
    template:
      data:
        key: '{{ .clientId }}'
        secret: '{{ .clientSecret }}'
