apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-db-config
  namespace: development
spec:
  data:
    - remoteRef:
        key: forgejo-app
        property: password
      secretKey: password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-development
  target:
    template:
      data:
        database: PASSWD={{ .password }}
