apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin
  namespace: development
spec:
  data:
    - remoteRef:
        key: forgejo/admin/username
      secretKey: username
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: forgejo-admin-password
        property: password
      secretKey: password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-development
  target:
    template:
      data:
        password: '{{ .password }}'
        username: '{{ .username }}'
