apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin
  namespace: development
spec:
  data:
    - remoteRef:
        key: forgejo/admin/username
      secretKey: username
    - remoteRef:
        key: forgejo/admin/password
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
