apiVersion: v1
kind: Secret
metadata:
  labels:
    app: forgejo
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: forgejo
    version: 14.0.3
  name: forgejo-inline-config
  namespace: development
stringData:
  _generals_: |-
    APP_NAME=Forgejo: Beyond coding. We forge.
    RUN_MODE=prod
  actions: ENABLED=true
  cache: |-
    ADAPTER=memory
    HOST=
  database: |-
    DB_TYPE=postgres
    HOST=forgejo-rw:5432
    NAME=forgejo
    USER=forgejo
  federation: ENABLED=true
  mailer: |-
    ENABLED=true
    FROM=Forgejo <noreply@trdos.me>
    PROTOCOL=smtp
    SMTP_ADDR=stalwart.mail.svc.cluster.local
    SMTP_PORT=25
  metrics: ENABLED=false
  oauth2_client: |-
    ACCOUNT_LINKING=auto
    ENABLE_AUTO_REGISTRATION=true
    USERNAME=preferred_username
  packages: ENABLED=true
  queue: |-
    CONN_STR=
    TYPE=level
  repository: ROOT=/data/git/gitea-repositories
  security: INSTALL_LOCK=true
  server: |-
    APP_DATA_PATH=/data
    DOMAIN=git.trdos.me
    ENABLE_PPROF=false
    HTTP_PORT=3000
    LFS_START_SERVER=true
    PROTOCOL=http
    ROOT_URL=https://git.trdos.me/
    SSH_DOMAIN=git.trdos.me
    SSH_LISTEN_PORT=2222
    SSH_PORT=22
    START_SSH_SERVER=true
  service: |-
    ALLOW_ONLY_EXTERNAL_REGISTRATION=true
    DISABLE_REGISTRATION=false
    ENABLE_INTERNAL_SIGNIN=false
    SHOW_REGISTRATION_BUTTON=false
  session: |-
    PROVIDER=db
    PROVIDER_CONFIG=
type: Opaque
