apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-b2-postgres
  namespace: media
spec:
  data:
    - remoteRef:
        key: backblaze/bucket/application_key_id
      secretKey: ACCESS_KEY_ID
    - remoteRef:
        key: backblaze/bucket/application_key
      secretKey: ACCESS_SECRET_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
