apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr
  namespace: media
spec:
  data:
    - remoteRef:
        key: sonarr
      secretKey: SONARR__AUTH__APIKEY
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: sonarr-app
        property: password
      secretKey: SONARR__POSTGRES__PASSWORD
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-media
