apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync--sonarr--sonarr
  namespace: media
spec:
  data:
    - remoteRef:
        key: volsync/restic/password
      secretKey: restic
    - remoteRef:
        key: backblaze/bucket/application_key_id
      secretKey: id
    - remoteRef:
        key: backblaze/bucket/application_key
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    template:
      data:
        AWS_ACCESS_KEY_ID: '{{ .id }}'
        AWS_DEFAULT_REGION: us-west-004
        AWS_SECRET_ACCESS_KEY: '{{ .password }}'
        RESTIC_PASSWORD: '{{ .restic }}'
        RESTIC_REPOSITORY: s3:https://s3.us-west-004.backblazeb2.com/trdos-me--volsync/volsync--sonarr--sonarr
