apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat
  namespace: ai
spec:
  data:
    - remoteRef:
        key: ai/librechat/session-secret
      secretKey: session_secret
    - remoteRef:
        key: ai/librechat/session-iv
      secretKey: session_iv
    - remoteRef:
        key: ai/librechat/jwt-secret
      secretKey: jwt_secret
    - remoteRef:
        key: ai/librechat/client-secret
      secretKey: oidc_secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    template:
      data:
        CREDS_IV: '{{ .session_iv }}'
        CREDS_KEY: '{{ .session_secret }}'
        JWT_SECRET: '{{ .jwt_secret }}'
        OPENID_CLIENT_SECRET: '{{ .oidc_secret }}'
