apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat
  namespace: ai
spec:
  data:
    - remoteRef:
        key: librechat
        property: client-secret
      secretKey: oidc_secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-identity
  target:
    template:
      data:
        OPENID_CLIENT_SECRET: '{{ .oidc_secret }}'
