apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-jwt
  namespace: ai
spec:
  dataFrom:
    - rewrite:
        - regexp:
            source: password
            target: JWT_SECRET
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: librechat-jwt
  refreshPolicy: CreatedOnce
