apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-creds-key
  namespace: ai
spec:
  dataFrom:
    - rewrite:
        - regexp:
            source: password
            target: CREDS_KEY
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: librechat-creds-key
  refreshPolicy: CreatedOnce
