apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: librechat-creds-key
  namespace: ai
spec:
  allowRepeat: true
  digits: 64
  length: 64
  noUpper: true
  symbols: 0
