apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: volsync--librechat--librechat-mongodb-src
  namespace: ai
spec:
  restic:
    copyMethod: Direct
    moverSecurityContext:
      fsGroup: 101
    pruneIntervalDays: 8
    repository: volsync--librechat--librechat-mongodb
    retain:
      daily: 1
      monthly: 1
      weekly: 1
      yearly: 1
  sourcePVC: data-librechat-mongodb-0
  trigger:
    schedule: 0 4 * * *
