apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ryot-admin-token
  namespace: media
spec:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: ryot-admin-token
  refreshPolicy: CreatedOnce
