apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ryot
  namespace: media
spec:
  data:
    - remoteRef:
        key: ryot-app
        property: password
      secretKey: DATABASE_URL
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-media
  target:
    template:
      data:
        DATABASE_URL: postgresql://ryot:{{ .DATABASE_URL }}@ryot-rw.media.svc.cluster.local:5432/ryot
