apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: ryot-admin-token
  namespace: media
spec:
  allowRepeat: true
  digits: 10
  length: 40
  noUpper: false
  symbols: 0
