apiVersion: v1
data:
  mosquitto.conf: |-
    listener 1883
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mosquitto
  name: mosquitto
  namespace: home
