apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mosquitto
  name: mosquitto
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
