apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
  namespace: media
spec:
  data:
    - remoteRef:
        key: prowlarr
      secretKey: PROWLARR__AUTH__APIKEY
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: prowlarr-app
        property: password
      secretKey: PROWLARR__POSTGRES__PASSWORD
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-media
