apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/controller: mooncord
    app.kubernetes.io/instance: mooncord
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mooncord
  name: mooncord
  namespace: printing
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: mooncord
      app.kubernetes.io/instance: mooncord
      app.kubernetes.io/name: mooncord
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: mooncord
        app.kubernetes.io/instance: mooncord
        app.kubernetes.io/name: mooncord
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: MOONRAKER_URL
              value: ws://voron.internal:7125/websocket
          envFrom:
            - secretRef:
                name: mooncord
          image: ghcr.io/eliteschwein/mooncord:latest
          name: mooncord
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      serviceAccountName: mooncord
