apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mooncord
  namespace: printing
spec:
  data:
    - remoteRef:
        key: printing/mooncord/discord-token
      secretKey: DISCORD_TOKEN
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
