apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-internal
  namespace: kube-system
spec:
  data:
    - remoteRef:
        key: adguard/admin/password
      secretKey: ADGUARD_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
