apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: external-dns-internal
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-dns
  name: external-dns-internal
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 7979
      protocol: TCP
      targetPort: http
    - name: http-webhook
      port: 8080
      protocol: TCP
      targetPort: http-webhook
  selector:
    app.kubernetes.io/instance: external-dns-internal
    app.kubernetes.io/name: external-dns
  type: ClusterIP
