apiVersion: v1
data:
  config.yaml: |
    connectivity:
      checker:
        interval: 1m
        target: 1.1.1.1:53
    debug: false
    endpoints:
    - conditions:
      - '[STATUS] == any(200, 302, 401)'
      group: internal
      interval: 1m
      name: actual
      url: https://actual.trdos.me
    - conditions:
      - '[STATUS] == any(200, 302, 401)'
      group: internal
      interval: 1m
      name: adguard
      url: https://adguard.trdos.me
    - conditions:
      - '[STATUS] == 200'
      group: internal
      interval: 1m
      name: alertmanager
      url: https://alertmanager.trdos.me
    - conditions:
      - '[STATUS] == 200'
      group: internal
      interval: 1m
      name: argo
      url: https://argocd.trdos.me
    - conditions:
      - '[STATUS] == any(200, 302, 401)'
      group: internal
      interval: 1m
      name: firefly
      url: https://firefly.trdos.me
    - client:
        dns-resolver: tcp://1.1.1.1:53
      conditions:
      - '[STATUS] == 200'
      group: external
      interval: 1m
      name: gatus
      url: https://gatus.trdos.me
    - conditions:
      - '[STATUS] == 200'
      group: internal
      interval: 1m
      name: grafana
      url: https://grafana.trdos.me
    - conditions:
      - '[STATUS] == any(200, 302, 401)'
      group: internal
      interval: 1m
      name: ha
      url: https://hass.trdos.me
    - conditions:
      - '[STATUS] == 200'
      group: internal
      interval: 1m
      name: keycloak
      url: https://keycloak.trdos.me
    - conditions:
      - '[STATUS] == 200'
      group: internal
      interval: 1m
      name: mealie
      url: https://mealie.trdos.me
    - conditions:
      - '[STATUS] == 200'
      group: internal
      interval: 1m
      name: oauth2-proxy
      url: https://oauth2.trdos.me/ping
    - conditions:
      - '[STATUS] == 200'
      group: internal
      interval: 1m
      name: prometheus
      url: https://prometheus.trdos.me
    - conditions:
      - '[STATUS] == 200'
      group: internal
      interval: 1m
      name: rook-ceph
      url: https://rook.trdos.me
    - conditions:
      - '[STATUS] == 401'
      group: internal
      interval: 1m
      name: stalwart
      url: https://mail.trdos.me
    - conditions:
      - '[STATUS] == 200'
      group: internal
      interval: 1m
      name: sure
      url: https://sure.trdos.me
    metrics: true
    storage:
      caching: true
      path: $GATUS_DB_URI
      type: postgres
    ui:
      header: Status
      title: Status | Gatus
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: gatus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gatus
  name: gatus
  namespace: observability
