apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus
  namespace: observability
spec:
  dataFrom:
    - extract:
        key: gatus-app
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-observability
  target:
    template:
      data:
        GATUS_DB_URI: '{{ .uri }}'
