apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: multus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: multus
  name: multus
  namespace: kube-system
