apiVersion: v1
data:
  config: |
    artifactRepository:
      s3:
        accessKeySecret:
          key: AWS_ACCESS_KEY_ID
          name: argo-workflows-bucket
        secretKeySecret:
          key: AWS_SECRET_ACCESS_KEY
          name: argo-workflows-bucket
        bucket: argo-workflows
        endpoint: rook-ceph-rgw-ceph-objectstore.storage.svc.cluster.local
        insecure: true
    metricsConfig:
      enabled: true
      path: /metrics
      port: 9090
      ignoreErrors: false
      secure: false
    persistence:
      archive: true
      postgresql:
        database: argo-workflows
        host: argo-workflows-rw
        passwordSecret:
          key: password
          name: argo-workflows-db
        port: "5432"
        userNameSecret:
          key: username
          name: argo-workflows-db
    workflowDefaults:
      spec:
        archiveLogs: true
    nodeEvents:
      enabled: true
    workflowEvents:
      enabled: true
    failedPodRestart:
      enabled: false
      maxRestarts: 3
kind: ConfigMap
metadata:
  labels:
    app: workflow-controller
    app.kubernetes.io/component: workflow-controller
    app.kubernetes.io/instance: argo-workflows
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-workflows-cm
    app.kubernetes.io/part-of: argo-workflows
  name: argo-workflows-workflow-controller-configmap
  namespace: cicd
