apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-harbor
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: harbor/robot/secret
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: argo-workflows-harbor
    template:
      data:
        config.json: '{"auths":{"harbor.trdos.me":{"auth":"{{ printf "robot$push:%s" .password | b64enc }}"}}}'
