apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-artifacts
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: argo-workflows/s3/access-key
      secretKey: access_key
    - remoteRef:
        key: argo-workflows/s3/secret-key
      secretKey: secret_key
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: argo-workflows-bucket
    template:
      data:
        AWS_ACCESS_KEY_ID: '{{ .access_key }}'
        AWS_SECRET_ACCESS_KEY: '{{ .secret_key }}'
