apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-github
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: github/update-bot/token
      secretKey: GITHUB_TOKEN
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: argo-workflows-github
