apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-harbor
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: harbor/robot/username
      secretKey: username
    - remoteRef:
        key: harbor/robot/password
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: argo-workflows-harbor
    template:
      data:
        config.json: '{"auths":{"harbor.trdos.me":{"password":"{{ .password }}","username":"{{ .username }}"}}}'
