apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-db
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: argo-workflows-app
        property: password
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-cicd
  target:
    template:
      data:
        password: '{{ .password }}'
        username: argo-workflows
