apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deps-update-nix
  namespace: cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: ceph-block
