apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-and-push
  namespace: cicd
spec:
  arguments:
    parameters:
      - name: repo-url
      - default: main
        name: revision
      - name: image-name
  entrypoint: ci-pipeline
  serviceAccountName: argo-workflows-ci
  templates:
    - name: ci-pipeline
      steps:
        - - name: clone
            template: clone
        - - name: build-push
            template: build-push
    - container:
        args:
          - git clone {{workflow.parameters.repo-url}} /workspace/src && cd /workspace/src && git checkout {{workflow.parameters.revision}}
        command:
          - sh
          - -c
        image: alpine/git:2.47.2@sha256:062a01ad7a0eb17cff382bc5e26086b4d710e56dfdfdf001109a49b6d9bd378c
        volumeMounts:
          - mountPath: /workspace
            name: workspace
      name: clone
    - container:
        args:
          - |
            cd /workspace/src
            mkdir -p /etc/nix
            echo "experimental-features = nix-command flakes" > /etc/nix/nix.conf
            echo "filter-syscalls = false" >> /etc/nix/nix.conf
            result=$(nix build ".#legacyPackages.x86_64-linux.images.{{workflow.parameters.image-name}}.copyToRegistry" --no-pure-eval --print-out-paths -L)
            $result/bin/copy-to-registry
        command:
          - sh
          - -c
        env:
          - name: REGISTRY_AUTH_FILE
            value: /registry-auth/config.json
        image: nixos/nix:2.28.3@sha256:e623d73af9cac82d1b50784c83e0cf2a4b83bfd2cfe8d5b67809a2fc94e043ac
        resources:
          limits:
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 4Gi
        volumeMounts:
          - mountPath: /workspace
            name: workspace
          - mountPath: /registry-auth
            name: registry-auth
            readOnly: true
      name: build-push
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: ceph-block
  volumes:
    - name: registry-auth
      secret:
        secretName: argo-workflows-harbor
