apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: smartctl-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-smartctl-exporter
    release: prometheus
  name: smartctl-exporter
  namespace: observability
spec:
  attachMetadata:
    node: true
  endpoints:
    - interval: 60s
      path: /metrics
      port: http
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node
      scheme: http
      scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
      - observability
  selector:
    matchLabels:
      app.kubernetes.io/instance: smartctl-exporter
      app.kubernetes.io/name: prometheus-smartctl-exporter
