apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: cicd
spec:
  jetstream:
    persistence:
      accessMode: ReadWriteOnce
      storageClassName: ceph-block
      volumeSize: 5Gi
    replicas: 1
    streamConfig: |
      maxMsgs: 1000000
      maxAge: 72h
      replicas: 1
      duplicates: 300s
    version: 2.10.10
