apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-webhook-secret
  namespace: cicd
spec:
  data:
    - remoteRef:
        key: forgejo/webhook/secret
      secretKey: secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
