apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared-tunnel
  namespace: kube-system
spec:
  endpoints:
    - dnsName: external.trdos.me
      recordType: CNAME
      targets:
        - ref+pulumistateapi://cloudflare_index__zeroTrustTunnelCloudflared_ZeroTrustTunnelCloudflared/main/outputs/id?organization=pulumbus&project=millionaire&stack=prod+.cfargotunnel.com
