apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: cloudflared
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudflared
  name: cloudflared
  namespace: kube-system
