apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubernetes-mail
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: external-secrets-kubernetes
          namespace: security
      remoteNamespace: mail
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          namespace: security
          type: ConfigMap
