apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: kavita
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kavita
  name: kavita
  namespace: media
