apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: rook-ceph-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ceph-csi
  name: ceph-csi-cephfs-nodeplugin-sa
  namespace: storage
