{
 "title": "Frigate",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Frigate Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "frigate_service_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inference Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frigate_detector_inference_speed_seconds*1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(frigate_cpu_usage_percent)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(frigate_mem_usage_percent)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Recording Storage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frigate_storage_used_bytes{storage=\"/media/frigate/recordings\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "frigate_storage_free_bytes{storage=\"/media/frigate/recordings\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Inference Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "frigate_detector_inference_speed_seconds",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg_over_time(frigate_detector_inference_speed_seconds[30m])",
     "legendFormat": "Average over 30min"
    }
   ]
  },
  {
   "title": "Number of events last 7 days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "round(increase(frigate_camera_events_total[7d]))",
     "legendFormat": "{{camera}} {{label}}"
    }
   ]
  },
  {
   "title": "Detection FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    { "expr": "frigate_detection_fps", "legendFormat": "{{camera_name}}" },
    { "expr": "frigate_detection_total_fps", "legendFormat": "Total" },
    {
     "expr": "avg_over_time(frigate_detection_total_fps[30m])",
     "legendFormat": "Average over 30min"
    }
   ]
  },
  {
   "title": "Number of events last 24 hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "round(increase(frigate_camera_events_total[24h]))",
     "legendFormat": "{{camera}} {{label}}"
    }
   ]
  },
  {
   "title": "Total Detection Frames Processed over 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "tfp" } },
   "targets": [
    {
     "expr": "sum_over_time(frigate_detection_fps[24h])",
     "legendFormat": "{{camera_name}}"
    }
   ]
  },
  {
   "title": "Number of events last hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "increase(frigate_camera_events_total[1h])",
     "legendFormat": "{{camera}} {{label}}"
    }
   ]
  },
  {
   "title": "Camera FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    { "expr": "frigate_camera_fps", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Number of events 10mins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "increase(frigate_camera_events_total[10m])",
     "legendFormat": "{{camera}} {{label}}"
    }
   ]
  },
  {
   "title": "Skipped FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    { "expr": "frigate_skipped_fps", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Number of events Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    { "expr": "frigate_camera_events_total", "legendFormat": "{{camera}} {{label}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (frigate_cpu_usage_percent{type=~\"Other\"})",
     "legendFormat": "Other Processes"
    },
    {
     "expr": "sum by (name, process, cmdline) (frigate_cpu_usage_percent{type!~\"Other\", pid!~\"frigate.full_system\"})",
     "legendFormat": "{{name}} | {{process}} | {{cmdline}}"
    }
   ]
  },
  {
   "title": "Storage Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "frigate_storage_total_bytes", "legendFormat": "{{storage}}" }
   ]
  },
  {
   "title": "Storage Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "frigate_storage_used_bytes", "legendFormat": "{{storage}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name, process, cmdline) (frigate_mem_usage_percent{type!~\"Other\", pid!~\"frigate.full_system\"})",
     "legendFormat": "{{name}} | {{process}} | {{cmdline}}"
    },
    {
     "expr": "sum(frigate_mem_usage_percent{type=~\"Other\"})",
     "legendFormat": "Other Processes"
    }
   ]
  },
  {
   "title": "Storage Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "frigate_storage_free_bytes", "legendFormat": "{{storage}}" }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"frigate\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sum(frigate_cpu_usage_percent)", "legendFormat": "Total" },
    {
     "expr": "sum(avg_over_time(frigate_cpu_usage_percent[1h]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Audio dBFS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    { "expr": "frigate_audio_dBFS", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sum(frigate_mem_usage_percent)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Audio RMS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    { "expr": "frigate_audio_rms", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Number Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "count(frigate_cpu_usage_percent)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(frigate_mem_usage_percent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    { "expr": "frigate_bandwidth_usages_kBps", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Device Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "frigate_device_temperature", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "GPU utilisation %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "frigate_gpu_usage_percent", "legendFormat": "{{gpu_name}}" }
   ]
  },
  {
   "title": "GPU memory usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "frigate_gpu_mem_usage_percent", "legendFormat": "{{gpu_name}}" }
   ]
  }
 ]
}