apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: games-webdav
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: games-webdav
  name: games-webdav
  namespace: media
