apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: multi-scrobbler
  namespace: media
spec:
  data:
    - remoteRef:
        key: maloja/api-key
      secretKey: maloja_api_key
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    template:
      data:
        MALOJA_API_KEY: '{{ .maloja_api_key }}'
