apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--multi-scrobbler--multi-scrobbler-dst
  namespace: media
spec:
  restic:
    copyMethod: Direct
    destinationPVC: multi-scrobbler
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--multi-scrobbler--multi-scrobbler
  trigger:
    manual: "1"
