apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jitsi-jicofo
  namespace: media
spec:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: jitsi-jicofo
  refreshPolicy: CreatedOnce
