apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jitsi-prosody-jicofo
  namespace: media
spec:
  data:
    - remoteRef:
        key: jitsi-jicofo
        property: password
      secretKey: jicofo
    - remoteRef:
        key: jitsi-component
        property: password
      secretKey: component
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-media
  target:
    template:
      data:
        JICOFO_AUTH_PASSWORD: '{{ .jicofo }}'
        JICOFO_AUTH_USER: focus
        JICOFO_COMPONENT_SECRET: '{{ .component }}'
