apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-klipper-exporter
  namespace: printing
spec:
  endpoints:
    - interval: 30s
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-klipper-exporter
