apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: prometheus-klipper-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-klipper-exporter
  name: prometheus-klipper-exporter
  namespace: printing
