apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: prometheus-klipper-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-klipper-exporter
    app.kubernetes.io/service: prometheus-klipper-exporter
  name: prometheus-klipper-exporter
  namespace: printing
spec:
  ports:
    - name: metrics
      port: 9101
      protocol: TCP
      targetPort: 9101
  selector:
    app.kubernetes.io/controller: prometheus-klipper-exporter
    app.kubernetes.io/instance: prometheus-klipper-exporter
    app.kubernetes.io/name: prometheus-klipper-exporter
  type: ClusterIP
