apiVersion: v1
data:
  serve.json: '{"TCP":{"443":{"TCPForward":"cilium-gateway-internal.kube-system.svc.cluster.local:443"},"80":{"TCPForward":"cilium-gateway-internal.kube-system.svc.cluster.local:80"}}}'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: tailscale-front
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tailscale-front
  name: tailscale-front
  namespace: tailscale
