apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/controller: tailscale-front
    app.kubernetes.io/instance: tailscale-front
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tailscale-front
  name: tailscale-front
  namespace: tailscale
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: tailscale-front
      app.kubernetes.io/instance: tailscale-front
      app.kubernetes.io/name: tailscale-front
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/configMaps: 76a5472b53e35510bc58887a1b5a37b31a7b188732b1a306d751df95ef762663
      labels:
        app.kubernetes.io/controller: tailscale-front
        app.kubernetes.io/instance: tailscale-front
        app.kubernetes.io/name: tailscale-front
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  key: TS_AUTHKEY
                  name: tailscale-front-authkey
            - name: TS_EXTRA_ARGS
              value: --login-server=https://headscale.trdos.me
            - name: TS_HOSTNAME
              value: internal-gateway
            - name: TS_KUBE_SECRET
              value: ""
            - name: TS_SERVE_CONFIG
              value: /config/serve.json
            - name: TS_STATE_DIR
              value: /var/lib/tailscale
            - name: TS_USERSPACE
              value: "true"
          image: ghcr.io/tailscale/tailscale:v1.98.4
          name: tailscale
          volumeMounts:
            - mountPath: /config/serve.json
              name: serve
              readOnly: true
              subPath: serve.json
            - mountPath: /var/lib/tailscale
              name: state
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostAliases:
        - hostnames:
            - headscale.trdos.me
          ip: 178.104.61.137
      hostIPC: false
      hostNetwork: false
      hostPID: false
      serviceAccountName: tailscale-front
      volumes:
        - configMap:
            name: tailscale-front
          name: serve
        - name: state
          persistentVolumeClaim:
            claimName: tailscale-front
