apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/controller: tailscale-front
    app.kubernetes.io/instance: tailscale-front
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tailscale-front
  name: tailscale-front
  namespace: tailscale
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: tailscale-front
      app.kubernetes.io/instance: tailscale-front
      app.kubernetes.io/name: tailscale-front
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: tailscale-front
        app.kubernetes.io/instance: tailscale-front
        app.kubernetes.io/name: tailscale-front
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  key: TS_AUTHKEY
                  name: tailscale-front-authkey
            - name: TS_DEST_IP
              value: 192.168.50.241
            - name: TS_EXTRA_ARGS
              value: --login-server=https://headscale.trdos.me
            - name: TS_HOSTNAME
              value: internal-gateway
            - name: TS_KUBE_SECRET
              value: ""
            - name: TS_STATE_DIR
              value: /var/lib/tailscale
            - name: TS_USERSPACE
              value: "false"
          image: ghcr.io/tailscale/tailscale:v1.98.4
          name: tailscale
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /dev/net/tun
              name: dev-net-tun
            - mountPath: /var/lib/tailscale
              name: state
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostAliases:
        - hostnames:
            - headscale.trdos.me
          ip: 178.104.61.137
      hostIPC: false
      hostNetwork: false
      hostPID: false
      serviceAccountName: tailscale-front
      volumes:
        - hostPath:
            path: /dev/net/tun
          name: dev-net-tun
        - name: state
          persistentVolumeClaim:
            claimName: tailscale-front
