apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: tailscale-front
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tailscale-front
  name: tailscale-front
  namespace: tailscale
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
