apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: atuin-tristan
  namespace: development
spec:
  data:
    - match:
        remoteRef:
          remoteKey: atuin/tristan/password
        secretKey: password
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: bitwarden
  selector:
    secret:
      name: atuin-tristan
