apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: atuin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: atuin
  name: atuin
  namespace: development
spec:
  endpoints:
    - interval: 1m
      path: /metrics
      port: metrics
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - development
  selector:
    matchLabels:
      app.kubernetes.io/instance: atuin
      app.kubernetes.io/name: atuin
      app.kubernetes.io/service: atuin
