apiVersion: v1
data:
  config.toml: |
    [authentication.fallback-admin]
    secret = "%{env:ADMIN_SECRET}%"
    user = "admin"

    [config]
    local-keys = [
        "store.*",
        "storage.*",
        "server.*",
        "directory.*",
        "authentication.fallback-admin.*",
        "tracer.*",
        "metrics.prometheus.*",
        "session.*",
        "queue.*",
        "config.local-keys.*",
    ]

    [directory.internal]
    store = "rocksdb"
    type = "internal"

    [metrics.prometheus]
    enable = true

    [queue.route.relay]
    address = "smtp.protonmail.ch"
    port = 587
    protocol = "smtp"
    type = "relay"

    [queue.route.relay.auth]
    secret = "%{env:SMTP_TOKEN}%"
    username = "noreply@trdos.me"

    [queue.route.relay.tls]
    allow-invalid-certs = false
    implicit = false

    [server.listener.management]
    bind = ["[::]:8080"]
    protocol = "http"

    [server.listener.smtp]
    bind = ["[::]:25"]
    protocol = "smtp"

    [session.rcpt]
    relay = true

    [storage]
    blob = "rocksdb"
    data = "rocksdb"
    directory = "internal"
    fts = "rocksdb"
    lookup = "rocksdb"

    [store.rocksdb]
    compression = "lz4"
    path = "/data"
    type = "rocksdb"

    [tracer.stdout]
    ansi = false
    enable = true
    level = "info"
    type = "stdout"

    [queue.strategy]
    route = [{else = "'relay'"}]
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: stalwart
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: stalwart
  name: stalwart
  namespace: mail
