apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart
  namespace: mail
spec:
  data:
    - remoteRef:
        key: stalwart/smtp/token
      secretKey: SMTP_TOKEN
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: stalwart/admin/password
      secretKey: ADMIN_SECRET
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
