apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: volsync--stalwart--stalwart-src
  namespace: mail
spec:
  restic:
    copyMethod: Direct
    moverSecurityContext:
      fsGroup: 101
    pruneIntervalDays: 8
    repository: volsync--stalwart--stalwart
    retain:
      daily: 1
      monthly: 1
      weekly: 1
      yearly: 1
  sourcePVC: stalwart
  trigger:
    schedule: 0 4 * * *
