apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: toolhive
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: toolhive-operator
    app.kubernetes.io/part-of: toolhive-operator
  name: toolhive-operator-leader-election-rolebinding
  namespace: ai
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: toolhive-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: toolhive-operator
    namespace: ai
