apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: registry-api
    app.kubernetes.io/managed-by: toolhive-operator
    app.kubernetes.io/name: toolhive-registry-api
  name: toolhive-registry-api
  namespace: ai
