# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys
import pulumi
import pulumi.runtime
from typing import Optional, Sequence, Union, overload

if sys.version_info >= (3, 11):
    pass
else:
    pass
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ["ItemSecureNoteArgs", "ItemSecureNote"]


@pulumi.input_type
class ItemSecureNoteArgs:
    def __init__(
        __self__,
        *,
        collection_ids: Optional[
            pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]
        ] = None,
        favorite: Optional[pulumi.Input[_builtins.bool]] = None,
        fields: Optional[
            pulumi.Input[Sequence[pulumi.Input["ItemSecureNoteFieldArgs"]]]
        ] = None,
        folder_id: Optional[pulumi.Input[_builtins.str]] = None,
        item_secure_note_id: Optional[pulumi.Input[_builtins.str]] = None,
        name: Optional[pulumi.Input[_builtins.str]] = None,
        notes: Optional[pulumi.Input[_builtins.str]] = None,
        organization_id: Optional[pulumi.Input[_builtins.str]] = None,
        reprompt: Optional[pulumi.Input[_builtins.bool]] = None,
    ):
        """
        The set of arguments for constructing a ItemSecureNote resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] collection_ids: Identifier of the collections the item belongs to.
        :param pulumi.Input[_builtins.bool] favorite: Mark as a Favorite to have item appear at the top of your Vault in the UI.
        :param pulumi.Input[Sequence[pulumi.Input['ItemSecureNoteFieldArgs']]] fields: Extra fields.
        :param pulumi.Input[_builtins.str] folder_id: Identifier of the folder.
        :param pulumi.Input[_builtins.str] item_secure_note_id: Identifier.
        :param pulumi.Input[_builtins.str] name: Name.
        :param pulumi.Input[_builtins.str] notes: Notes.
        :param pulumi.Input[_builtins.str] organization_id: Identifier of the organization.
        :param pulumi.Input[_builtins.bool] reprompt: Require master password 're-prompt' when displaying secret in the UI.
        """
        if collection_ids is not None:
            pulumi.set(__self__, "collection_ids", collection_ids)
        if favorite is not None:
            pulumi.set(__self__, "favorite", favorite)
        if fields is not None:
            pulumi.set(__self__, "fields", fields)
        if folder_id is not None:
            pulumi.set(__self__, "folder_id", folder_id)
        if item_secure_note_id is not None:
            pulumi.set(__self__, "item_secure_note_id", item_secure_note_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if notes is not None:
            pulumi.set(__self__, "notes", notes)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if reprompt is not None:
            pulumi.set(__self__, "reprompt", reprompt)

    @_builtins.property
    @pulumi.getter(name="collectionIds")
    def collection_ids(
        self,
    ) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Identifier of the collections the item belongs to.
        """
        return pulumi.get(self, "collection_ids")

    @collection_ids.setter
    def collection_ids(
        self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]
    ):
        pulumi.set(self, "collection_ids", value)

    @_builtins.property
    @pulumi.getter
    def favorite(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Mark as a Favorite to have item appear at the top of your Vault in the UI.
        """
        return pulumi.get(self, "favorite")

    @favorite.setter
    def favorite(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "favorite", value)

    @_builtins.property
    @pulumi.getter
    def fields(
        self,
    ) -> Optional[pulumi.Input[Sequence[pulumi.Input["ItemSecureNoteFieldArgs"]]]]:
        """
        Extra fields.
        """
        return pulumi.get(self, "fields")

    @fields.setter
    def fields(
        self,
        value: Optional[
            pulumi.Input[Sequence[pulumi.Input["ItemSecureNoteFieldArgs"]]]
        ],
    ):
        pulumi.set(self, "fields", value)

    @_builtins.property
    @pulumi.getter(name="folderId")
    def folder_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Identifier of the folder.
        """
        return pulumi.get(self, "folder_id")

    @folder_id.setter
    def folder_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "folder_id", value)

    @_builtins.property
    @pulumi.getter(name="itemSecureNoteId")
    def item_secure_note_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Identifier.
        """
        return pulumi.get(self, "item_secure_note_id")

    @item_secure_note_id.setter
    def item_secure_note_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "item_secure_note_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def notes(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Notes.
        """
        return pulumi.get(self, "notes")

    @notes.setter
    def notes(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "notes", value)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Identifier of the organization.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "organization_id", value)

    @_builtins.property
    @pulumi.getter
    def reprompt(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Require master password 're-prompt' when displaying secret in the UI.
        """
        return pulumi.get(self, "reprompt")

    @reprompt.setter
    def reprompt(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "reprompt", value)


@pulumi.input_type
class _ItemSecureNoteState:
    def __init__(
        __self__,
        *,
        attachments: Optional[
            pulumi.Input[Sequence[pulumi.Input["ItemSecureNoteAttachmentArgs"]]]
        ] = None,
        collection_ids: Optional[
            pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]
        ] = None,
        creation_date: Optional[pulumi.Input[_builtins.str]] = None,
        deleted_date: Optional[pulumi.Input[_builtins.str]] = None,
        favorite: Optional[pulumi.Input[_builtins.bool]] = None,
        fields: Optional[
            pulumi.Input[Sequence[pulumi.Input["ItemSecureNoteFieldArgs"]]]
        ] = None,
        folder_id: Optional[pulumi.Input[_builtins.str]] = None,
        item_secure_note_id: Optional[pulumi.Input[_builtins.str]] = None,
        name: Optional[pulumi.Input[_builtins.str]] = None,
        notes: Optional[pulumi.Input[_builtins.str]] = None,
        organization_id: Optional[pulumi.Input[_builtins.str]] = None,
        reprompt: Optional[pulumi.Input[_builtins.bool]] = None,
        revision_date: Optional[pulumi.Input[_builtins.str]] = None,
    ):
        """
        Input properties used for looking up and filtering ItemSecureNote resources.
        :param pulumi.Input[Sequence[pulumi.Input['ItemSecureNoteAttachmentArgs']]] attachments: List of item attachments.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] collection_ids: Identifier of the collections the item belongs to.
        :param pulumi.Input[_builtins.str] creation_date: Date the item was created.
        :param pulumi.Input[_builtins.str] deleted_date: Date the item was deleted.
        :param pulumi.Input[_builtins.bool] favorite: Mark as a Favorite to have item appear at the top of your Vault in the UI.
        :param pulumi.Input[Sequence[pulumi.Input['ItemSecureNoteFieldArgs']]] fields: Extra fields.
        :param pulumi.Input[_builtins.str] folder_id: Identifier of the folder.
        :param pulumi.Input[_builtins.str] item_secure_note_id: Identifier.
        :param pulumi.Input[_builtins.str] name: Name.
        :param pulumi.Input[_builtins.str] notes: Notes.
        :param pulumi.Input[_builtins.str] organization_id: Identifier of the organization.
        :param pulumi.Input[_builtins.bool] reprompt: Require master password 're-prompt' when displaying secret in the UI.
        :param pulumi.Input[_builtins.str] revision_date: Last time the item was updated.
        """
        if attachments is not None:
            pulumi.set(__self__, "attachments", attachments)
        if collection_ids is not None:
            pulumi.set(__self__, "collection_ids", collection_ids)
        if creation_date is not None:
            pulumi.set(__self__, "creation_date", creation_date)
        if deleted_date is not None:
            pulumi.set(__self__, "deleted_date", deleted_date)
        if favorite is not None:
            pulumi.set(__self__, "favorite", favorite)
        if fields is not None:
            pulumi.set(__self__, "fields", fields)
        if folder_id is not None:
            pulumi.set(__self__, "folder_id", folder_id)
        if item_secure_note_id is not None:
            pulumi.set(__self__, "item_secure_note_id", item_secure_note_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if notes is not None:
            pulumi.set(__self__, "notes", notes)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if reprompt is not None:
            pulumi.set(__self__, "reprompt", reprompt)
        if revision_date is not None:
            pulumi.set(__self__, "revision_date", revision_date)

    @_builtins.property
    @pulumi.getter
    def attachments(
        self,
    ) -> Optional[pulumi.Input[Sequence[pulumi.Input["ItemSecureNoteAttachmentArgs"]]]]:
        """
        List of item attachments.
        """
        return pulumi.get(self, "attachments")

    @attachments.setter
    def attachments(
        self,
        value: Optional[
            pulumi.Input[Sequence[pulumi.Input["ItemSecureNoteAttachmentArgs"]]]
        ],
    ):
        pulumi.set(self, "attachments", value)

    @_builtins.property
    @pulumi.getter(name="collectionIds")
    def collection_ids(
        self,
    ) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Identifier of the collections the item belongs to.
        """
        return pulumi.get(self, "collection_ids")

    @collection_ids.setter
    def collection_ids(
        self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]
    ):
        pulumi.set(self, "collection_ids", value)

    @_builtins.property
    @pulumi.getter(name="creationDate")
    def creation_date(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Date the item was created.
        """
        return pulumi.get(self, "creation_date")

    @creation_date.setter
    def creation_date(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "creation_date", value)

    @_builtins.property
    @pulumi.getter(name="deletedDate")
    def deleted_date(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Date the item was deleted.
        """
        return pulumi.get(self, "deleted_date")

    @deleted_date.setter
    def deleted_date(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "deleted_date", value)

    @_builtins.property
    @pulumi.getter
    def favorite(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Mark as a Favorite to have item appear at the top of your Vault in the UI.
        """
        return pulumi.get(self, "favorite")

    @favorite.setter
    def favorite(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "favorite", value)

    @_builtins.property
    @pulumi.getter
    def fields(
        self,
    ) -> Optional[pulumi.Input[Sequence[pulumi.Input["ItemSecureNoteFieldArgs"]]]]:
        """
        Extra fields.
        """
        return pulumi.get(self, "fields")

    @fields.setter
    def fields(
        self,
        value: Optional[
            pulumi.Input[Sequence[pulumi.Input["ItemSecureNoteFieldArgs"]]]
        ],
    ):
        pulumi.set(self, "fields", value)

    @_builtins.property
    @pulumi.getter(name="folderId")
    def folder_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Identifier of the folder.
        """
        return pulumi.get(self, "folder_id")

    @folder_id.setter
    def folder_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "folder_id", value)

    @_builtins.property
    @pulumi.getter(name="itemSecureNoteId")
    def item_secure_note_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Identifier.
        """
        return pulumi.get(self, "item_secure_note_id")

    @item_secure_note_id.setter
    def item_secure_note_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "item_secure_note_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def notes(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Notes.
        """
        return pulumi.get(self, "notes")

    @notes.setter
    def notes(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "notes", value)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Identifier of the organization.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "organization_id", value)

    @_builtins.property
    @pulumi.getter
    def reprompt(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Require master password 're-prompt' when displaying secret in the UI.
        """
        return pulumi.get(self, "reprompt")

    @reprompt.setter
    def reprompt(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "reprompt", value)

    @_builtins.property
    @pulumi.getter(name="revisionDate")
    def revision_date(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Last time the item was updated.
        """
        return pulumi.get(self, "revision_date")

    @revision_date.setter
    def revision_date(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "revision_date", value)


@pulumi.type_token("bitwarden:index/itemSecureNote:ItemSecureNote")
class ItemSecureNote(pulumi.CustomResource):
    @overload
    def __init__(
        __self__,
        resource_name: str,
        opts: Optional[pulumi.ResourceOptions] = None,
        collection_ids: Optional[
            pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]
        ] = None,
        favorite: Optional[pulumi.Input[_builtins.bool]] = None,
        fields: Optional[
            pulumi.Input[
                Sequence[
                    pulumi.Input[
                        Union["ItemSecureNoteFieldArgs", "ItemSecureNoteFieldArgsDict"]
                    ]
                ]
            ]
        ] = None,
        folder_id: Optional[pulumi.Input[_builtins.str]] = None,
        item_secure_note_id: Optional[pulumi.Input[_builtins.str]] = None,
        name: Optional[pulumi.Input[_builtins.str]] = None,
        notes: Optional[pulumi.Input[_builtins.str]] = None,
        organization_id: Optional[pulumi.Input[_builtins.str]] = None,
        reprompt: Optional[pulumi.Input[_builtins.bool]] = None,
        __props__=None,
    ):
        """
        Create a ItemSecureNote resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] collection_ids: Identifier of the collections the item belongs to.
        :param pulumi.Input[_builtins.bool] favorite: Mark as a Favorite to have item appear at the top of your Vault in the UI.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ItemSecureNoteFieldArgs', 'ItemSecureNoteFieldArgsDict']]]] fields: Extra fields.
        :param pulumi.Input[_builtins.str] folder_id: Identifier of the folder.
        :param pulumi.Input[_builtins.str] item_secure_note_id: Identifier.
        :param pulumi.Input[_builtins.str] name: Name.
        :param pulumi.Input[_builtins.str] notes: Notes.
        :param pulumi.Input[_builtins.str] organization_id: Identifier of the organization.
        :param pulumi.Input[_builtins.bool] reprompt: Require master password 're-prompt' when displaying secret in the UI.
        """
        ...

    @overload
    def __init__(
        __self__,
        resource_name: str,
        args: Optional[ItemSecureNoteArgs] = None,
        opts: Optional[pulumi.ResourceOptions] = None,
    ):
        """
        Create a ItemSecureNote resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param ItemSecureNoteArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...

    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(
            ItemSecureNoteArgs, pulumi.ResourceOptions, *args, **kwargs
        )
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(
        __self__,
        resource_name: str,
        opts: Optional[pulumi.ResourceOptions] = None,
        collection_ids: Optional[
            pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]
        ] = None,
        favorite: Optional[pulumi.Input[_builtins.bool]] = None,
        fields: Optional[
            pulumi.Input[
                Sequence[
                    pulumi.Input[
                        Union["ItemSecureNoteFieldArgs", "ItemSecureNoteFieldArgsDict"]
                    ]
                ]
            ]
        ] = None,
        folder_id: Optional[pulumi.Input[_builtins.str]] = None,
        item_secure_note_id: Optional[pulumi.Input[_builtins.str]] = None,
        name: Optional[pulumi.Input[_builtins.str]] = None,
        notes: Optional[pulumi.Input[_builtins.str]] = None,
        organization_id: Optional[pulumi.Input[_builtins.str]] = None,
        reprompt: Optional[pulumi.Input[_builtins.bool]] = None,
        __props__=None,
    ):
        opts = pulumi.ResourceOptions.merge(
            _utilities.get_resource_opts_defaults(), opts
        )
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError(
                "Expected resource options to be a ResourceOptions instance"
            )
        if opts.id is None:
            if __props__ is not None:
                raise TypeError(
                    "__props__ is only valid when passed in combination with a valid opts.id to get an existing resource"
                )
            __props__ = ItemSecureNoteArgs.__new__(ItemSecureNoteArgs)

            __props__.__dict__["collection_ids"] = collection_ids
            __props__.__dict__["favorite"] = favorite
            __props__.__dict__["fields"] = fields
            __props__.__dict__["folder_id"] = folder_id
            __props__.__dict__["item_secure_note_id"] = item_secure_note_id
            __props__.__dict__["name"] = name
            __props__.__dict__["notes"] = (
                None if notes is None else pulumi.Output.secret(notes)
            )
            __props__.__dict__["organization_id"] = organization_id
            __props__.__dict__["reprompt"] = reprompt
            __props__.__dict__["attachments"] = None
            __props__.__dict__["creation_date"] = None
            __props__.__dict__["deleted_date"] = None
            __props__.__dict__["revision_date"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["notes"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ItemSecureNote, __self__).__init__(
            "bitwarden:index/itemSecureNote:ItemSecureNote",
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package(),
        )

    @staticmethod
    def get(
        resource_name: str,
        id: pulumi.Input[str],
        opts: Optional[pulumi.ResourceOptions] = None,
        attachments: Optional[
            pulumi.Input[
                Sequence[
                    pulumi.Input[
                        Union[
                            "ItemSecureNoteAttachmentArgs",
                            "ItemSecureNoteAttachmentArgsDict",
                        ]
                    ]
                ]
            ]
        ] = None,
        collection_ids: Optional[
            pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]
        ] = None,
        creation_date: Optional[pulumi.Input[_builtins.str]] = None,
        deleted_date: Optional[pulumi.Input[_builtins.str]] = None,
        favorite: Optional[pulumi.Input[_builtins.bool]] = None,
        fields: Optional[
            pulumi.Input[
                Sequence[
                    pulumi.Input[
                        Union["ItemSecureNoteFieldArgs", "ItemSecureNoteFieldArgsDict"]
                    ]
                ]
            ]
        ] = None,
        folder_id: Optional[pulumi.Input[_builtins.str]] = None,
        item_secure_note_id: Optional[pulumi.Input[_builtins.str]] = None,
        name: Optional[pulumi.Input[_builtins.str]] = None,
        notes: Optional[pulumi.Input[_builtins.str]] = None,
        organization_id: Optional[pulumi.Input[_builtins.str]] = None,
        reprompt: Optional[pulumi.Input[_builtins.bool]] = None,
        revision_date: Optional[pulumi.Input[_builtins.str]] = None,
    ) -> "ItemSecureNote":
        """
        Get an existing ItemSecureNote resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ItemSecureNoteAttachmentArgs', 'ItemSecureNoteAttachmentArgsDict']]]] attachments: List of item attachments.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] collection_ids: Identifier of the collections the item belongs to.
        :param pulumi.Input[_builtins.str] creation_date: Date the item was created.
        :param pulumi.Input[_builtins.str] deleted_date: Date the item was deleted.
        :param pulumi.Input[_builtins.bool] favorite: Mark as a Favorite to have item appear at the top of your Vault in the UI.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ItemSecureNoteFieldArgs', 'ItemSecureNoteFieldArgsDict']]]] fields: Extra fields.
        :param pulumi.Input[_builtins.str] folder_id: Identifier of the folder.
        :param pulumi.Input[_builtins.str] item_secure_note_id: Identifier.
        :param pulumi.Input[_builtins.str] name: Name.
        :param pulumi.Input[_builtins.str] notes: Notes.
        :param pulumi.Input[_builtins.str] organization_id: Identifier of the organization.
        :param pulumi.Input[_builtins.bool] reprompt: Require master password 're-prompt' when displaying secret in the UI.
        :param pulumi.Input[_builtins.str] revision_date: Last time the item was updated.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ItemSecureNoteState.__new__(_ItemSecureNoteState)

        __props__.__dict__["attachments"] = attachments
        __props__.__dict__["collection_ids"] = collection_ids
        __props__.__dict__["creation_date"] = creation_date
        __props__.__dict__["deleted_date"] = deleted_date
        __props__.__dict__["favorite"] = favorite
        __props__.__dict__["fields"] = fields
        __props__.__dict__["folder_id"] = folder_id
        __props__.__dict__["item_secure_note_id"] = item_secure_note_id
        __props__.__dict__["name"] = name
        __props__.__dict__["notes"] = notes
        __props__.__dict__["organization_id"] = organization_id
        __props__.__dict__["reprompt"] = reprompt
        __props__.__dict__["revision_date"] = revision_date
        return ItemSecureNote(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def attachments(
        self,
    ) -> pulumi.Output[Sequence["outputs.ItemSecureNoteAttachment"]]:
        """
        List of item attachments.
        """
        return pulumi.get(self, "attachments")

    @_builtins.property
    @pulumi.getter(name="collectionIds")
    def collection_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Identifier of the collections the item belongs to.
        """
        return pulumi.get(self, "collection_ids")

    @_builtins.property
    @pulumi.getter(name="creationDate")
    def creation_date(self) -> pulumi.Output[_builtins.str]:
        """
        Date the item was created.
        """
        return pulumi.get(self, "creation_date")

    @_builtins.property
    @pulumi.getter(name="deletedDate")
    def deleted_date(self) -> pulumi.Output[_builtins.str]:
        """
        Date the item was deleted.
        """
        return pulumi.get(self, "deleted_date")

    @_builtins.property
    @pulumi.getter
    def favorite(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Mark as a Favorite to have item appear at the top of your Vault in the UI.
        """
        return pulumi.get(self, "favorite")

    @_builtins.property
    @pulumi.getter
    def fields(
        self,
    ) -> pulumi.Output[Optional[Sequence["outputs.ItemSecureNoteField"]]]:
        """
        Extra fields.
        """
        return pulumi.get(self, "fields")

    @_builtins.property
    @pulumi.getter(name="folderId")
    def folder_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Identifier of the folder.
        """
        return pulumi.get(self, "folder_id")

    @_builtins.property
    @pulumi.getter(name="itemSecureNoteId")
    def item_secure_note_id(self) -> pulumi.Output[_builtins.str]:
        """
        Identifier.
        """
        return pulumi.get(self, "item_secure_note_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def notes(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Notes.
        """
        return pulumi.get(self, "notes")

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Identifier of the organization.
        """
        return pulumi.get(self, "organization_id")

    @_builtins.property
    @pulumi.getter
    def reprompt(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Require master password 're-prompt' when displaying secret in the UI.
        """
        return pulumi.get(self, "reprompt")

    @_builtins.property
    @pulumi.getter(name="revisionDate")
    def revision_date(self) -> pulumi.Output[_builtins.str]:
        """
        Last time the item was updated.
        """
        return pulumi.get(self, "revision_date")
