apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: owncast
  namespace: media
spec:
  data:
    - remoteRef:
        key: owncast/stream-key
      secretKey: OWNCAST_STREAM_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
