apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: owncast
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: owncast
  name: owncast
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
