apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: owncast
  namespace: media
spec:
  data:
    - match:
        remoteRef:
          remoteKey: owncast/stream-key
        secretKey: OWNCAST_STREAM_KEY
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: bitwarden
  selector:
    secret:
      name: owncast
