apiVersion: v1
data:
  recyclarr.yml: |-
    radarr:
      radarr:
        api_key: !env_var RADARR_API_KEY
        base_url: http://radarr.media.svc.cluster.local
        custom_format_groups:
          add:
          - trash_id: 15b1cf0b6f1a1493856a4355907affee
        quality_definition:
          type: sqp-streaming
        quality_profiles:
        - reset_unmatched_scores:
            enabled: true
          trash_id: e91c9adaca0231493f4af0d571b907f9
    sonarr:
      sonarr:
        api_key: !env_var SONARR_API_KEY
        base_url: http://sonarr.media.svc.cluster.local
        custom_format_groups:
          add:
          - trash_id: 85fae4a2294965b75710ef2989c850eb
          - trash_id: 59c3af66780d08332fdc64e68297098f
        quality_definition:
          type: series
        quality_profiles:
        - reset_unmatched_scores:
            enabled: true
          trash_id: 72dae194fc92bf828f32cde7744e51a1
        - reset_unmatched_scores:
            enabled: true
          trash_id: d1498e7d189fbe6c7110ceaabb7473e6
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: recyclarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: recyclarr
  name: recyclarr
  namespace: media
