apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
  namespace: media
spec:
  data:
    - remoteRef:
        key: radarr-apikey
        property: apikey
      secretKey: radarr
    - remoteRef:
        key: sonarr-apikey
        property: apikey
      secretKey: sonarr
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-media
  target:
    template:
      data:
        secrets.yml: |
          radarr: '{{ .radarr }}'
          sonarr: '{{ .sonarr }}'
