apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
  namespace: media
spec:
  data:
    - remoteRef:
        key: radarr-apikey
        property: apikey
      secretKey: RADARR_API_KEY
    - remoteRef:
        key: sonarr-apikey
        property: apikey
      secretKey: SONARR_API_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-media
