apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: music-assistant
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: music-assistant
  name: music-assistant
  namespace: media
