apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-oidc
  namespace: finance
spec:
  data:
    - remoteRef:
        key: actual
        property: client-secret
      secretKey: client_secret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
