apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: keycloak-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak-operator
  name: keycloak-operator-manager-role
rules:
  - apiGroups:
      - keycloak.hostzero.com
    resources:
      - clusterkeycloakinstances
      - clusterkeycloakrealms
      - keycloakclients
      - keycloakclientscopes
      - keycloakcomponents
      - keycloakgroups
      - keycloakidentityproviders
      - keycloakinstances
      - keycloakorganizations
      - keycloakprotocolmappers
      - keycloakrealms
      - keycloakroles
      - keycloakrolemappings
      - keycloakusercredentials
      - keycloakusers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - keycloak.hostzero.com
    resources:
      - clusterkeycloakinstances/status
      - clusterkeycloakrealms/status
      - keycloakclients/status
      - keycloakclientscopes/status
      - keycloakcomponents/status
      - keycloakgroups/status
      - keycloakidentityproviders/status
      - keycloakinstances/status
      - keycloakorganizations/status
      - keycloakprotocolmappers/status
      - keycloakrealms/status
      - keycloakroles/status
      - keycloakrolemappings/status
      - keycloakusercredentials/status
      - keycloakusers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - keycloak.hostzero.com
    resources:
      - clusterkeycloakinstances/finalizers
      - clusterkeycloakrealms/finalizers
      - keycloakclients/finalizers
      - keycloakclientscopes/finalizers
      - keycloakcomponents/finalizers
      - keycloakgroups/finalizers
      - keycloakidentityproviders/finalizers
      - keycloakinstances/finalizers
      - keycloakorganizations/finalizers
      - keycloakprotocolmappers/finalizers
      - keycloakrealms/finalizers
      - keycloakroles/finalizers
      - keycloakrolemappings/finalizers
      - keycloakusercredentials/finalizers
      - keycloakusers/finalizers
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
