apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: keycloak-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak-operator
  name: keycloak-operator-metrics
  namespace: identity
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: keycloak-operator
    app.kubernetes.io/name: keycloak-operator
  type: ClusterIP
