apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autobrr
  namespace: media
spec:
  data:
    - remoteRef:
        key: autobrr-apikey
        property: apikey
      secretKey: session_secret.txt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-media
    - remoteRef:
        key: autobrr-app
        property: password
      secretKey: db_password.txt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-media
