apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: bulwark
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bulwark
    app.kubernetes.io/service: bulwark
  name: bulwark
  namespace: mail
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/controller: bulwark
    app.kubernetes.io/instance: bulwark
    app.kubernetes.io/name: bulwark
  type: ClusterIP
