apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: volsync--seerr--seerr-src
  namespace: media
spec:
  restic:
    copyMethod: Direct
    moverSecurityContext:
      fsGroup: 101
    pruneIntervalDays: 8
    repository: volsync--seerr--seerr
    retain:
      daily: 1
      monthly: 1
      weekly: 1
      yearly: 1
  sourcePVC: seerr
  trigger:
    schedule: 0 4 * * *
