apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--seerr--seerr-dst
  namespace: media
spec:
  restic:
    copyMethod: Direct
    destinationPVC: seerr
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--seerr--seerr
  trigger:
    manual: "1"
