apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/exclude: "true"
  name: http-to-https-external
  namespace: kube-system
spec:
  hostnames:
    - '*.trdos.me'
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: http
  rules:
    - filters:
        - requestRedirect:
            scheme: https
            statusCode: 301
          type: RequestRedirect
