apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: org-bridge
  namespace: home
spec:
  data:
    - remoteRef:
        key: syncthing/api-key
      secretKey: SYNCTHING_API_KEY
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: baikal/admin-username
      secretKey: CALDAV_USERNAME
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: baikal/admin-password
      secretKey: CALDAV_PASSWORD
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
