apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: org-bridge
  namespace: home
spec:
  data:
    - remoteRef:
        key: syncthing
        property: STGUIAPIKEY
      secretKey: syncthing_key
    - remoteRef:
        key: baikal
        property: BAIKAL_ADMIN_PASSWORD
      secretKey: caldav_password
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-home
  target:
    template:
      data:
        CALDAV_PASSWORD: '{{ .caldav_password }}'
        CALDAV_USERNAME: admin
        SYNCTHING_API_KEY: '{{ .syncthing_key }}'
