apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: org-bridge
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: org-bridge
  name: org-bridge
  namespace: home
