apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: kube-prometheus-stack-kube-etcd
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-86.1.0
    heritage: Helm
    k8s-app: etcd-server
    release: prometheus
  name: prometheus-kube-prometheus-kube-etcd
  namespace: kube-system
subsets:
  - addresses:
      - ip: 192.168.50.204
      - ip: 192.168.50.53
      - ip: 192.168.50.105
    ports:
      - name: http-metrics
        port: 2381
        protocol: TCP
