apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-immich
  namespace: media
spec:
  cluster:
    name: immich
  databaseReclaimPolicy: retain
  ensure: present
  extensions:
    - ensure: present
      name: vector
    - ensure: present
      name: vchord
    - ensure: present
      name: cube
    - ensure: present
      name: earthdistance
  name: immich
  owner: immich
