apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: immich-dragonfly
  namespace: media
spec:
  replicas: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
