apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-server
  namespace: media
spec:
  data:
    - remoteRef:
        key: immich-app
        property: password
      secretKey: db_password.txt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-media
