apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-config
  namespace: media
spec:
  data:
    - remoteRef:
        key: immich
        property: client-secret
      secretKey: client_secret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
  target:
    template:
      data:
        immich.json: '{"oauth":{"autoLaunch":false,"autoRegister":true,"buttonText":"Login with Keycloak","clientId":"immich","clientSecret":"{{ .client_secret }}","enabled":true,"issuerUrl":"https://keycloak.trdos.me/realms/default","roleClaim":"immich_role","scope":"openid email profile"},"passwordLogin":{"enabled":true},"server":{"externalDomain":"https://immich.trdos.me"}}'
