apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--komga--komga-dst
  namespace: media
spec:
  restic:
    copyMethod: Direct
    destinationPVC: komga
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--komga--komga
  trigger:
    manual: "1"
