apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
  namespace: home
spec:
  data:
    - remoteRef:
        key: frigate/cameras
        property: username
      secretKey: FRIGATE_RTSP_USER
    - remoteRef:
        key: frigate/cameras
        property: password
      secretKey: FRIGATE_RTSP_PASS
    - remoteRef:
        key: frigate/cameras
        property: front_ip
      secretKey: FRIGATE_CAM_FRONT_IP
    - remoteRef:
        key: frigate/cameras
        property: back_ip
      secretKey: FRIGATE_CAM_BACK_IP
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
