apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: dvd-webdav
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dvd-webdav
  name: dvd-webdav
  namespace: media
