apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: audiobookshelf-oidc
  namespace: media
spec:
  data:
    - remoteRef:
        key: audiobookshelf
        property: client-secret
      secretKey: client_secret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
