apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: volsync--audiobookshelf--audiobookshelf-src
  namespace: media
spec:
  restic:
    copyMethod: Direct
    moverSecurityContext:
      fsGroup: 101
    pruneIntervalDays: 8
    repository: volsync--audiobookshelf--audiobookshelf
    retain:
      daily: 1
      monthly: 1
      weekly: 1
      yearly: 1
  sourcePVC: audiobookshelf
  trigger:
    schedule: 0 4 * * *
