apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: observability
spec:
  data:
    - remoteRef:
        key: grafana
        property: client-secret
      secretKey: client_secret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-identity
  target:
    template:
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: '{{ .client_secret }}'
