apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  data:
    - remoteRef:
        key: grafana
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    template:
      data:
        admin-password: '{{ .password }}'
        admin-user: admin
